import { mkdir, rename, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const appRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const runtimeConfigPath = join(appRoot, "www", "pos-runtime-config.js");

function escapeForJavaScript(value) {
  return JSON.stringify(value)
    .replaceAll("<", "\\u003c")
    .replaceAll(">", "\\u003e")
    .replaceAll("&", "\\u0026")
    .replaceAll("\u2028", "\\u2028")
    .replaceAll("\u2029", "\\u2029");
}

export async function writeRuntimeAsset(runtimeConfig) {
  const publicConfig = {
    runtime: runtimeConfig.runtimeMode,
    serverUrl: runtimeConfig.serverUrl ?? null,
  };
  const contents = [
    "/* Generated by POS Mobile tooling. Contains only the public POS origin. */",
    `window.__CLEANHUB_POS_RUNTIME__ = Object.freeze(${escapeForJavaScript(publicConfig)});`,
    "",
  ].join("\n");
  const temporaryPath = `${runtimeConfigPath}.tmp`;

  await mkdir(dirname(runtimeConfigPath), { recursive: true });
  await writeFile(temporaryPath, contents, { encoding: "utf8", mode: 0o600 });
  await rename(temporaryPath, runtimeConfigPath);

  return runtimeConfigPath;
}

export const paths = {
  appRoot,
  runtimeConfigPath,
};
