export const webAdminRoutes = {
  home: "/",
  login: "/login",
  apiHealth: "/api-health",
  saas: {
    home: "/saas",
    profile: "/saas/profile",
    tenants: "/saas/tenants",
    newTenant: "/saas/tenants/new",
    users: "/saas/users",
    auditLogs: "/saas/audit-logs",
    feedbackTickets: "/saas/feedback-tickets",
    todos: "/saas/todos",
    config: {
      tenants: "/saas/tenants",
      featureFlags: "/saas/config/feature-flags",
      localization: "/saas/config/localization",
      platformSettings: "/saas/config/platform-settings",
    },
    system: {
      logs: "/saas/system/logs",
      backups: "/saas/system/backups",
      security: "/saas/system/security",
    },
  },
  tenant: {
    home: "/tenant",
    profile: "/tenant/profile",
    orders: "/tenant/orders",
    customers: "/tenant/customers",
    products: "/tenant/products",
    newProduct: "/tenant/products/new",
    product: (productId: string) =>
      `/tenant/products/${encodeURIComponent(productId)}`,
    discounts: "/tenant/discounts",
    newDiscount: "/tenant/discounts/new",
    discount: (discountId: string) =>
      `/tenant/discounts/${encodeURIComponent(discountId)}`,
    pointOfSale: {
      home: "/tenant/point-of-sale",
      devices: "/tenant/point-of-sale/devices",
      registerSessions: "/tenant/point-of-sale/register-sessions",
      settings: "/tenant/point-of-sale/settings",
    },
    branches: "/tenant/branches",
    services: "/tenant/services",
    newService: "/tenant/services/new",
    hardware: "/tenant/hardware",
    newHardware: "/tenant/hardware/new",
    hardwareDevice: (hardwareId: string) =>
      `/tenant/hardware/${encodeURIComponent(hardwareId)}`,
    notifications: "/tenant/notifications",
    reports: "/tenant/reports",
    finance: "/tenant/finance",
    config: {
      branches: "/tenant/branches",
      services: "/tenant/services",
      hardware: "/tenant/hardware",
    },
    system: {
      logs: "/tenant/system/logs",
      auditLog: (logId: string) =>
        `/tenant/system/logs/${encodeURIComponent(logId)}`,
      backups: "/tenant/system/backups",
      settings: "/tenant/system/settings",
      settingsSections: {
        general: "/tenant/system/settings",
        locations: "/tenant/system/settings/locations",
        pricing: "/tenant/system/settings/pricing",
        pointOfSale: "/tenant/system/settings/point-of-sale",
        hardware: "/tenant/system/settings/hardware",
        activityLog: "/tenant/system/settings/activity-log",
      },
      preferences: "/tenant/system/preferences",
    },
  },
} as const;
