export const posRoutes = {
  home: "/",
  login: "/login",
  workspace: "/",
  newIntake: "/new-intake",
  scan: "/scan",
  customers: "/customers",
  tickets: "/tickets",
  ticketDetail: (ticketId: string) => `/tickets/${ticketId}`,
  orders: "/orders",
  statistics: "/statistics",
  garments: "/garments",
  shiftHandover: "/shift-handover",
  notifications: "/notifications",
  settings: "/settings",
} as const;
