package com.cleanhub.pos.nativepos

/**
 * Cashier-facing copy for the native POS.
 *
 * The app was written in Chinese throughout, with a three-language picker that
 * reached only the PIN screen -- so a French cashier signed in through French
 * copy and then met Chinese for everything after it. Tenants already run in
 * French, so this is not hypothetical.
 *
 * This covers the checkout path a cashier meets during every sale: the till
 * itself, payment, receipts, hardware faults and the errors those raise.
 * Lower-traffic screens (settings, shift reports, the More tab) are still
 * Chinese-only and are listed in the review; they are reached by a manager who
 * can be trained, not by a cashier under queue pressure.
 *
 * Kotlin has no resource-bundle equivalent that works for this shape without
 * dragging in Android resources, and Android string resources cannot be
 * switched per terminal at runtime without recreating the Activity. A data
 * class keeps every language complete by construction: add a field and the
 * compiler names the three places to fill in.
 */
internal data class NativePosCopy(
    // --- status and connectivity ---
    val online: String,
    val offline: String,
    val offlineMode: String,
    val syncing: String,
    val synchronize: String,
    val pendingSalesSuffix: String,

    // --- sale screen ---
    val catalogTitle: String,
    val cartEmpty: String,
    val amountDue: String,
    val checkout: String,
    val cashTendered: String,
    val changeDue: String,
    val subtotal: String,
    val tax: String,
    val rounding: String,
    val total: String,

    // --- receipt delivery ---
    val receiptPrint: String,
    val receiptNone: String,
    val receiptQueued: String,

    // --- outcomes ---
    val saleSubmittedOnline: String,
    val saleQueuedOffline: String,
    val cashPaymentRecorded: String,

    // --- refusals the cashier can act on ---
    val tenderBelowTotal: String,
    val cartIsEmpty: String,
    val priceChanged: String,
    val shiftAndDrawerRequired: String,
    val requiresNetwork: String,
    val networkError: String,
    val genericFailure: String,
    val staleCatalogWarning: String,

    // --- hardware ---
    val printerNotConnected: String,
    val printerOutOfPaper: String,
    val printerCoverOpen: String,
    val printerOverheated: String,
    val drawerOpened: String,
    val drawerDisconnected: String,

    // --- bottom navigation and the More menu ---
    val tabWorkspace: String,
    val tabSale: String,
    val tabIntake: String,
    val tabTickets: String,
    val tabMore: String,
    val menuMore: String,
    val menuCustomers: String,
    val menuCatalog: String,
    val menuScan: String,
    val menuOrders: String,
    val menuOrderDetail: String,
    val menuStatistics: String,
    val menuNotifications: String,
    val menuShift: String,
    val menuSettings: String,
    val menuHardware: String,

    // --- ticket status, as the server names it ---
    val ticketDraft: String,
    val ticketPending: String,
    val ticketInProgress: String,
    val ticketReadyToPick: String,
    val ticketPickedUp: String,
    val ticketCancelled: String,
    val ticketUnknown: String,
    val itemPendingWash: String,
    val itemWashing: String,
    val itemDone: String,
    val itemReadyToPick: String,

    // --- ticket item types and priority ---
    val typeCloth: String,
    val typeCar: String,
    val typeShoe: String,
    val typeCarpet: String,
    val priorityCritical: String,
    val priorityUrgent: String,
    val priorityNormal: String,

    // --- hardware device types ---
    val devicePrinter: String,
    val deviceScanner: String,
    val deviceCashDrawer: String,

    // --- workspace, intake and ticket list ---
    val moreNeedsNetwork: String,
    val workspaceTitle: String,
    val workspaceOnlineHint: String,
    val workspaceOfflineHint: String,
    val metricCatalog: String,
    val metricPendingOrders: String,
    val metricFailedOrders: String,
    val cashSectionTitle: String,
    val cashReadyOffline: String,
    val cashCheckedOnline: String,
    val cashNeedsSync: String,
    val openTill: String,
    val synchronizing: String,
    val intakeTitle: String,
    val intakeOnlineHint: String,
    val intakeOfflineHint: String,
    val newCustomer: String,
    val newCustomerShort: String,
    val lookupTitle: String,
    val lookupHint: String,
    val lookupLabel: String,
    val lookupPlaceholder: String,
    val search: String,
    val customerRecord: String,
    val change: String,
    val contactDetails: String,
    val noContactDetails: String,
    val customerStatusActive: String,
    val customerStatusPrefix: String,
    val recentWork: String,
    val newestFirst: String,
    val noCachedTickets: String,
    val newOrder: String,
    val intakeEmptyTitle: String,
    val intakeEmptyDescription: String,
    val intakeNoMatchTitle: String,
    val intakeNoMatchDescription: String,
    val matchingCustomers: String,
    val matchingCustomersCount: String,
    val noPhoneOnFile: String,
    val select: String,
    val serviceOrder: String,
    val itemsCountSuffix: String,
    val expectedPickup: String,
    val continueProcessing: String,
    val ticketsTitle: String,
    val ticketsEmpty: String,
    val serviceTicket: String,
    val syncLocalData: String,

    // --- shift, register and cash movements ---
    val backToMore: String,
    val refreshing: String,
    val refreshStatus: String,
    val shiftTitle: String,
    val shiftIntro: String,
    val shiftOfflineNotice: String,
    val shiftLoading: String,
    val shiftLoadFailed: String,
    val reload: String,
    val staffShift: String,
    val shiftOpen: String,
    val shiftOnBreak: String,
    val shiftClosed: String,
    val clockingIn: String,
    val clockIn: String,
    val breakStarting: String,
    val breakStart: String,
    val clockOut: String,
    val breakEnding: String,
    val breakEnd: String,
    val registerTitle: String,
    val cashModeNone: String,
    val cashModeUntracked: String,
    val cashModePersonal: String,
    val cashModeShared: String,
    val openingFloatRequired: String,
    val openingFloatOptional: String,
    val openingFloatNeeded: String,
    val registerOpening: String,
    val openMyCashSession: String,
    val openRegister: String,
    val registerStatus: String,
    val thisTerminal: String,
    val opened: String,
    val notOpened: String,
    val cashSession: String,
    val myPersonalCash: String,
    val sharedDrawer: String,
    val expectedCash: String,
    val thisRegister: String,
    val netSales: String,
    val outstandingOrders: String,
    val awaitingProcessing: String,
    val cashInOut: String,
    val amountLabel: String,
    val reasonLabel: String,
    val recording: String,
    val payIn: String,
    val payOut: String,
    val countAndCloseMyCash: String,
    val closeRegisterZReport: String,
    val closeRegisterHint: String,
    val countedCashRequired: String,
    val countedCashOptional: String,
    val handoverNotes: String,
    val countedCashNeeded: String,
    val closing: String,
    val confirmClose: String,
    val notYet: String,
    val closeNeedsManager: String,
    val recentZReports: String,
    val varianceLabel: String,
    val localData: String,
    val cachedSummary: String,
    val confirmClockOutTitle: String,
    val confirmClockOutBody: String,
    val checkAgain: String,
    val confirmClockOut: String,
    val readyOnlineCash: String,
    val readyOfflineCash: String,
    val cashDisabledStore: String,
    val cashNeedsShiftOnline: String,
    val cashNeedsShiftOffline: String,
    val startMyShift: String,
    val shiftStarted: String,
    val drawerOpeningCash: String,
    val openDrawerAndSync: String,
    val openTicket: String,
)

private val COPY_ZH = NativePosCopy(
    online = "已联网",
    offline = "离线",
    offlineMode = "离线模式",
    syncing = "同步中",
    synchronize = "同步",
    pendingSalesSuffix = "待同步 %d 笔",
    catalogTitle = "商品目录",
    cartEmpty = "购物车为空。",
    amountDue = "应收金额",
    checkout = "结算",
    cashTendered = "实收现金",
    changeDue = "应找零",
    subtotal = "小计",
    tax = "税费",
    rounding = "抹零",
    total = "合计",
    receiptPrint = "打印小票",
    receiptNone = "不打小票",
    receiptQueued = "收据已加入本地打印队列。",
    saleSubmittedOnline = "现金订单已提交；如网络在响应中断开，将使用同一订单号安全补传。",
    saleQueuedOffline = "现金订单已写入本地队列；联网后将使用同一订单号安全同步。",
    cashPaymentRecorded = "现金收款已记录。",
    tenderBelowTotal = "实收金额不能少于应收金额。",
    cartIsEmpty = "购物车为空。",
    priceChanged = "价格、优惠或税费已更新，请重新确认结款。",
    shiftAndDrawerRequired = "现金收款需要已开始的班次和已打开的钱箱。",
    requiresNetwork = "该操作需要联网；恢复网络后即可继续。",
    networkError = "网络错误，请检查本机网络后重试。",
    genericFailure = "操作未完成：请检查网络或稍后重试。",
    staleCatalogWarning = "本机商品与价格已有 %d 小时未更新，请尽快同步后再继续销售。",
    printerNotConnected = "打印机未连接。",
    printerOutOfPaper = "打印机缺纸，请装入热敏纸后重试。",
    printerCoverOpen = "打印机仓盖未关闭。",
    printerOverheated = "打印机温度过高，请稍后重试。",
    drawerOpened = "钱箱已打开。",
    drawerDisconnected = "钱箱服务已断开，请刷新硬件状态后重试。",
    tabWorkspace = "工作台",
    tabSale = "收银",
    tabIntake = "开单",
    tabTickets = "工单",
    tabMore = "更多",
    menuMore = "更多",
    menuCustomers = "客户管理",
    menuCatalog = "商品与服务目录",
    menuScan = "扫码查询",
    menuOrders = "订单管理",
    menuOrderDetail = "订单详情",
    menuStatistics = "经营数据",
    menuNotifications = "通知中心",
    menuShift = "班次与收银",
    menuSettings = "终端设置",
    menuHardware = "打印与硬件",
    ticketDraft = "草稿",
    ticketPending = "待处理",
    ticketInProgress = "处理中",
    ticketReadyToPick = "待取件",
    ticketPickedUp = "已取件",
    ticketCancelled = "已取消",
    ticketUnknown = "异常",
    itemPendingWash = "待处理",
    itemWashing = "处理中",
    itemDone = "已完成",
    itemReadyToPick = "待取件",
    typeCloth = "衣物",
    typeCar = "车辆",
    typeShoe = "鞋类",
    typeCarpet = "地毯",
    priorityCritical = "紧急",
    priorityUrgent = "加急",
    priorityNormal = "普通",
    devicePrinter = "打印机",
    deviceScanner = "扫码器",
    deviceCashDrawer = "钱箱",
    moreNeedsNetwork = "%s 需要联网加载；当前仍可使用本机缓存的客户、目录和工单。",
    workspaceTitle = "工作台",
    workspaceOnlineHint = "设备已联网，可实时核验收银状态",
    workspaceOfflineHint = "设备离线，使用本机已缓存的收银数据",
    metricCatalog = "商品目录",
    metricPendingOrders = "待同步订单",
    metricFailedOrders = "异常订单",
    cashSectionTitle = "现金收银",
    cashReadyOffline = "班次和钱箱已就绪，可以安全离线收取现金。",
    cashCheckedOnline = "进入收银后会实时核验班次和钱箱状态。",
    cashNeedsSync = "恢复网络并同步班次和钱箱后，即可继续离线收银。",
    openTill = "进入收银",
    synchronizing = "正在同步…",
    intakeTitle = "客户接待",
    intakeOnlineHint = "查询客户档案，选择客户后创建服务工单。",
    intakeOfflineHint = "离线时可查询已缓存客户；创建客户和工单需要联网。",
    newCustomer = "＋ 新建客户",
    newCustomerShort = "新建客户",
    lookupTitle = "查询客户档案",
    lookupHint = "输入客户姓名、手机号或账户名称。",
    lookupLabel = "姓名、电话或账户",
    lookupPlaceholder = "例如：Awa Diop / 77 000 0000",
    search = "查询",
    customerRecord = "客户档案",
    change = "更换",
    contactDetails = "联系方式",
    noContactDetails = "未填写联系电话或邮箱",
    customerStatusActive = "客户状态：正常",
    customerStatusPrefix = "客户状态：%s",
    recentWork = "最近处理",
    newestFirst = "最新在上",
    noCachedTickets = "暂无已缓存的服务订单。创建第一笔订单后会显示在这里。",
    newOrder = "＋ 新增订单",
    intakeEmptyTitle = "输入客户信息开始查询",
    intakeEmptyDescription = "默认不会展示全部客户资料。请输入姓名、手机号或账户名称查找客户。",
    intakeNoMatchTitle = "未找到客户",
    intakeNoMatchDescription = "没有与“%s”匹配的已缓存客户。请核对信息或新建客户。",
    matchingCustomers = "匹配客户",
    matchingCustomersCount = "%d 条本机匹配结果，点击后继续开单。",
    noPhoneOnFile = "未填写手机号",
    select = "选择",
    serviceOrder = "服务订单",
    itemsCountSuffix = "%d 项",
    expectedPickup = "预计取件：%s",
    continueProcessing = "继续处理 ›",
    ticketsTitle = "工单",
    ticketsEmpty = "本机暂时没有已同步工单。",
    serviceTicket = "服务工单",
    syncLocalData = "同步本机数据",
    backToMore = "返回更多",
    refreshing = "正在刷新…",
    refreshStatus = "刷新状态",
    shiftTitle = "班次与收银",
    shiftIntro = "班次、收银台和现金盘点分别记录；开始班次后，再开启收银台即可安全进行现金收款。",
    shiftOfflineNotice = "当前离线：可继续销售已缓存商品，但班次、收银台和现金流水必须恢复联网后操作。",
    shiftLoading = "正在读取班次与收银台状态",
    shiftLoadFailed = "若加载失败，请确认设备联网后点击“刷新状态”。",
    reload = "重新加载",
    staffShift = "员工班次",
    shiftOpen = "当前上班中。可以开始休息，或继续收银。",
    shiftOnBreak = "当前处于休息中。结束休息后才能继续收银。",
    shiftClosed = "当前未开始班次。开始班次后，现金销售才能关联到本次交接。",
    clockingIn = "正在开始班次…",
    clockIn = "开始班次",
    breakStarting = "正在开始…",
    breakStart = "开始休息",
    clockOut = "结束班次",
    breakEnding = "正在结束休息…",
    breakEnd = "结束休息",
    registerTitle = "收银台",
    cashModeNone = "此终端未启用现金收款。可以查看收银台状态，但不能收取现金。",
    cashModeUntracked = "本终端接受现金，但门店不跟踪钱箱金额。",
    cashModePersonal = "本终端使用员工随身现金；每位员工需要开启自己的现金会话。",
    cashModeShared = "本终端使用共享钱箱；开启后可记录备用金、现金存入和现金支出。",
    openingFloatRequired = "开柜备用金 *",
    openingFloatOptional = "开柜备用金（可选）",
    openingFloatNeeded = "此门店要求填写开柜备用金后才能开启收银台。",
    registerOpening = "正在开启…",
    openMyCashSession = "开启我的现金会话",
    openRegister = "开启收银台",
    registerStatus = "收银台状态",
    thisTerminal = "本终端",
    opened = "已开启",
    notOpened = "未开启",
    cashSession = "现金会话",
    myPersonalCash = "我的随身现金",
    sharedDrawer = "共享钱箱",
    expectedCash = "系统应有现金",
    thisRegister = "本次收银台",
    netSales = "净销售额",
    outstandingOrders = "待收订单",
    awaitingProcessing = "等待处理",
    cashInOut = "现金存入 / 支出",
    amountLabel = "金额",
    reasonLabel = "原因（至少 3 个字）",
    recording = "正在记录…",
    payIn = "现金存入",
    payOut = "现金支出",
    countAndCloseMyCash = "盘点并关闭我的现金",
    closeRegisterZReport = "关闭收银台并生成 Z Report",
    closeRegisterHint = "关闭后会生成或更新本次交接记录。请确认实点金额。",
    countedCashRequired = "实点现金 *",
    countedCashOptional = "实点现金（可选）",
    handoverNotes = "交接备注（可选）",
    countedCashNeeded = "此门店要求填写实点现金后才能关闭。",
    closing = "正在关闭…",
    confirmClose = "确认关闭",
    notYet = "暂不关闭",
    closeNeedsManager = "请先由当前员工开启或关闭自己的现金会话；只有店主或经理可以最终关闭收银台。",
    recentZReports = "最近 Z Report",
    varianceLabel = "差额",
    localData = "本机数据",
    cachedSummary = "已缓存 %d 个商品；%d 笔现金订单等待同步。",
    confirmClockOutTitle = "确认结束班次？",
    confirmClockOutBody = "结束后需要重新输入 PIN 并开始班次，才能继续收银。",
    checkAgain = "再检查一下",
    confirmClockOut = "确认结束",
    readyOnlineCash = "准备在线现金收银",
    readyOfflineCash = "准备离线现金收银",
    cashDisabledStore = "此门店当前没有启用现金收款。请由管理员在门店 POS 设置中启用现金支付后重新同步。",
    cashNeedsShiftOnline = "现金订单需要关联已开始的班次和已打开的钱箱。",
    cashNeedsShiftOffline = "离线现金订单必须关联已开始的班次和已打开的钱箱，避免断网时的现金记录失去归属。",
    startMyShift = "开始我的班次",
    shiftStarted = "班次已开始。",
    drawerOpeningCash = "开箱现金",
    openDrawerAndSync = "打开钱箱并同步",
    openTicket = "查看并处理工单",

)

private val COPY_EN = NativePosCopy(
    online = "Online",
    offline = "Offline",
    offlineMode = "Offline mode",
    syncing = "Syncing",
    synchronize = "Sync",
    pendingSalesSuffix = "%d waiting to sync",
    catalogTitle = "Catalogue",
    cartEmpty = "The cart is empty.",
    amountDue = "Amount due",
    checkout = "Checkout",
    cashTendered = "Cash received",
    changeDue = "Change due",
    subtotal = "Subtotal",
    tax = "Tax",
    rounding = "Rounding",
    total = "Total",
    receiptPrint = "Print receipt",
    receiptNone = "No receipt",
    receiptQueued = "The receipt is in this terminal's print queue.",
    saleSubmittedOnline = "Cash order submitted. If the connection drops before the reply arrives, it is resent safely under the same order number.",
    saleQueuedOffline = "Cash order saved to this terminal. It syncs under the same order number once the network returns.",
    cashPaymentRecorded = "Cash payment recorded.",
    tenderBelowTotal = "Cash received cannot be less than the amount due.",
    cartIsEmpty = "The cart is empty.",
    priceChanged = "The price, discount or tax changed. Confirm the payment again.",
    shiftAndDrawerRequired = "Taking cash needs an open shift and an open drawer.",
    requiresNetwork = "This needs a connection. Try again once the network is back.",
    networkError = "Network error. Check this terminal's connection and try again.",
    genericFailure = "That did not finish. Check the network or try again shortly.",
    staleCatalogWarning = "Products and prices on this terminal are %d hours old. Sync before selling further.",
    printerNotConnected = "The printer is not connected.",
    printerOutOfPaper = "The printer is out of paper. Load thermal paper and try again.",
    printerCoverOpen = "The printer cover is open.",
    printerOverheated = "The printer is too hot. Try again shortly.",
    drawerOpened = "Cash drawer opened.",
    drawerDisconnected = "The cash drawer service disconnected. Refresh the hardware status and try again.",
    tabWorkspace = "Home",
    tabSale = "Till",
    tabIntake = "New ticket",
    tabTickets = "Tickets",
    tabMore = "More",
    menuMore = "More",
    menuCustomers = "Customers",
    menuCatalog = "Products and services",
    menuScan = "Scan to look up",
    menuOrders = "Orders",
    menuOrderDetail = "Order detail",
    menuStatistics = "Business figures",
    menuNotifications = "Notifications",
    menuShift = "Shift and cash",
    menuSettings = "Terminal settings",
    menuHardware = "Printing and hardware",
    ticketDraft = "Draft",
    ticketPending = "Waiting",
    ticketInProgress = "In progress",
    ticketReadyToPick = "Ready for pickup",
    ticketPickedUp = "Picked up",
    ticketCancelled = "Cancelled",
    ticketUnknown = "Unknown",
    itemPendingWash = "Waiting",
    itemWashing = "In progress",
    itemDone = "Done",
    itemReadyToPick = "Ready for pickup",
    typeCloth = "Clothing",
    typeCar = "Vehicle",
    typeShoe = "Shoes",
    typeCarpet = "Carpet",
    priorityCritical = "Critical",
    priorityUrgent = "Rush",
    priorityNormal = "Normal",
    devicePrinter = "Printer",
    deviceScanner = "Scanner",
    deviceCashDrawer = "Cash drawer",
    moreNeedsNetwork = "%s needs a connection. Cached customers, catalogue and tickets stay available on this terminal.",
    workspaceTitle = "Home",
    workspaceOnlineHint = "This terminal is online; till status is checked live.",
    workspaceOfflineHint = "This terminal is offline and using its cached till data.",
    metricCatalog = "Catalogue",
    metricPendingOrders = "Waiting to sync",
    metricFailedOrders = "Rejected",
    cashSectionTitle = "Cash till",
    cashReadyOffline = "Shift and drawer are ready; cash can be taken safely offline.",
    cashCheckedOnline = "Shift and drawer are checked live when you open the till.",
    cashNeedsSync = "Restore the network and sync the shift and drawer to take cash offline again.",
    openTill = "Open the till",
    synchronizing = "Syncing…",
    intakeTitle = "Customer intake",
    intakeOnlineHint = "Look up a customer, then create a service ticket.",
    intakeOfflineHint = "Offline you can search cached customers; creating a customer or ticket needs a connection.",
    newCustomer = "＋ New customer",
    newCustomerShort = "New customer",
    lookupTitle = "Find a customer",
    lookupHint = "Enter a name, phone number or account name.",
    lookupLabel = "Name, phone or account",
    lookupPlaceholder = "For example: Awa Diop / 77 000 0000",
    search = "Search",
    customerRecord = "Customer record",
    change = "Change",
    contactDetails = "Contact",
    noContactDetails = "No phone or email on file",
    customerStatusActive = "Status: active",
    customerStatusPrefix = "Status: %s",
    recentWork = "Recent work",
    newestFirst = "Newest first",
    noCachedTickets = "No cached service orders yet. The first one you create appears here.",
    newOrder = "＋ New order",
    intakeEmptyTitle = "Search to begin",
    intakeEmptyDescription = "The full customer list is not shown by default. Search by name, phone or account.",
    intakeNoMatchTitle = "No customer found",
    intakeNoMatchDescription = "No cached customer matches “%s”. Check the details or create a customer.",
    matchingCustomers = "Matching customers",
    matchingCustomersCount = "%d match on this terminal. Tap one to start a ticket.",
    noPhoneOnFile = "No phone on file",
    select = "Select",
    serviceOrder = "Service order",
    itemsCountSuffix = "%d items",
    expectedPickup = "Pickup: %s",
    continueProcessing = "Continue ›",
    ticketsTitle = "Tickets",
    ticketsEmpty = "No synced tickets on this terminal yet.",
    serviceTicket = "Service ticket",
    syncLocalData = "Sync this terminal",
    backToMore = "Back to More",
    refreshing = "Refreshing…",
    refreshStatus = "Refresh status",
    shiftTitle = "Shift and cash",
    shiftIntro = "Shift, register and cash count are recorded separately. Clock in, then open the register to take cash safely.",
    shiftOfflineNotice = "Offline: you can keep selling cached products, but shift, register and cash movements need a connection.",
    shiftLoading = "Loading shift and register status",
    shiftLoadFailed = "If this does not load, check the connection and tap “Refresh status”.",
    reload = "Reload",
    staffShift = "Staff shift",
    shiftOpen = "Clocked in. You can start a break or keep selling.",
    shiftOnBreak = "On break. End the break before selling again.",
    shiftClosed = "Not clocked in. Clock in so cash sales attach to this handover.",
    clockingIn = "Clocking in…",
    clockIn = "Clock in",
    breakStarting = "Starting…",
    breakStart = "Start break",
    clockOut = "Clock out",
    breakEnding = "Ending break…",
    breakEnd = "End break",
    registerTitle = "Register",
    cashModeNone = "Cash is not enabled on this terminal. You can view the register but not take cash.",
    cashModeUntracked = "This terminal takes cash, but the store does not track the drawer amount.",
    cashModePersonal = "This terminal uses personal cash floats; each member of staff opens their own cash session.",
    cashModeShared = "This terminal uses a shared drawer. Once open you can record the float, pay-ins and pay-outs.",
    openingFloatRequired = "Opening float *",
    openingFloatOptional = "Opening float (optional)",
    openingFloatNeeded = "This store requires an opening float before the register can be opened.",
    registerOpening = "Opening…",
    openMyCashSession = "Open my cash session",
    openRegister = "Open the register",
    registerStatus = "Register status",
    thisTerminal = "This terminal",
    opened = "Open",
    notOpened = "Closed",
    cashSession = "Cash session",
    myPersonalCash = "My personal float",
    sharedDrawer = "Shared drawer",
    expectedCash = "Expected cash",
    thisRegister = "This register",
    netSales = "Net sales",
    outstandingOrders = "Unpaid orders",
    awaitingProcessing = "Awaiting processing",
    cashInOut = "Pay in / pay out",
    amountLabel = "Amount",
    reasonLabel = "Reason (at least 3 characters)",
    recording = "Recording…",
    payIn = "Pay in",
    payOut = "Pay out",
    countAndCloseMyCash = "Count and close my cash",
    closeRegisterZReport = "Close the register and print a Z report",
    closeRegisterHint = "Closing creates or updates this handover record. Confirm the counted amount.",
    countedCashRequired = "Counted cash *",
    countedCashOptional = "Counted cash (optional)",
    handoverNotes = "Handover notes (optional)",
    countedCashNeeded = "This store requires a counted amount before closing.",
    closing = "Closing…",
    confirmClose = "Confirm closing",
    notYet = "Not yet",
    closeNeedsManager = "Each member of staff opens and closes their own cash session; only an owner or manager closes the register itself.",
    recentZReports = "Recent Z reports",
    varianceLabel = "Variance",
    localData = "This terminal's data",
    cachedSummary = "%d products cached; %d cash orders waiting to sync.",
    confirmClockOutTitle = "Clock out?",
    confirmClockOutBody = "You will need to enter your PIN and clock in again before selling.",
    checkAgain = "Let me check",
    confirmClockOut = "Clock out",
    readyOnlineCash = "Ready for online cash",
    readyOfflineCash = "Ready for offline cash",
    cashDisabledStore = "Cash is not enabled for this store. An administrator must enable cash in the store's POS settings, then sync again.",
    cashNeedsShiftOnline = "A cash order needs an open shift and an open drawer.",
    cashNeedsShiftOffline = "An offline cash order must attach to an open shift and an open drawer, so cash taken without a network still has an owner.",
    startMyShift = "Start my shift",
    shiftStarted = "Shift started.",
    drawerOpeningCash = "Opening cash",
    openDrawerAndSync = "Open the drawer and sync",
    openTicket = "Open the ticket",

)

private val COPY_FR = NativePosCopy(
    online = "En ligne",
    offline = "Hors ligne",
    offlineMode = "Mode hors ligne",
    syncing = "Synchronisation",
    synchronize = "Synchroniser",
    pendingSalesSuffix = "%d en attente de synchronisation",
    catalogTitle = "Catalogue",
    cartEmpty = "Le panier est vide.",
    amountDue = "Montant dû",
    checkout = "Encaisser",
    cashTendered = "Espèces reçues",
    changeDue = "Monnaie à rendre",
    subtotal = "Sous-total",
    tax = "Taxe",
    rounding = "Arrondi",
    total = "Total",
    receiptPrint = "Imprimer le reçu",
    receiptNone = "Sans reçu",
    receiptQueued = "Le reçu est dans la file d'impression de cette caisse.",
    saleSubmittedOnline = "Commande espèces envoyée. Si la connexion tombe avant la réponse, elle est renvoyée sous le même numéro de commande.",
    saleQueuedOffline = "Commande espèces enregistrée sur cette caisse. Elle sera synchronisée sous le même numéro dès le retour du réseau.",
    cashPaymentRecorded = "Paiement en espèces enregistré.",
    tenderBelowTotal = "Les espèces reçues ne peuvent pas être inférieures au montant dû.",
    cartIsEmpty = "Le panier est vide.",
    priceChanged = "Le prix, la remise ou la taxe a changé. Confirmez de nouveau le paiement.",
    shiftAndDrawerRequired = "Encaisser des espèces exige un service ouvert et un tiroir ouvert.",
    requiresNetwork = "Cette action demande une connexion. Réessayez dès le retour du réseau.",
    networkError = "Erreur réseau. Vérifiez la connexion de cette caisse et réessayez.",
    genericFailure = "L'opération n'a pas abouti. Vérifiez le réseau ou réessayez sous peu.",
    staleCatalogWarning = "Les produits et les prix de cette caisse datent de %d heures. Synchronisez avant de continuer à vendre.",
    printerNotConnected = "L'imprimante n'est pas connectée.",
    printerOutOfPaper = "L'imprimante n'a plus de papier. Chargez du papier thermique et réessayez.",
    printerCoverOpen = "Le capot de l'imprimante est ouvert.",
    printerOverheated = "L'imprimante est trop chaude. Réessayez sous peu.",
    drawerOpened = "Tiroir-caisse ouvert.",
    drawerDisconnected = "Le service du tiroir-caisse s'est déconnecté. Actualisez l'état du matériel et réessayez.",
    tabWorkspace = "Accueil",
    tabSale = "Caisse",
    tabIntake = "Nouveau bon",
    tabTickets = "Bons",
    tabMore = "Plus",
    menuMore = "Plus",
    menuCustomers = "Clients",
    menuCatalog = "Produits et services",
    menuScan = "Scanner pour rechercher",
    menuOrders = "Commandes",
    menuOrderDetail = "Détail de la commande",
    menuStatistics = "Chiffres d'activité",
    menuNotifications = "Notifications",
    menuShift = "Service et caisse",
    menuSettings = "Réglages de la caisse",
    menuHardware = "Impression et matériel",
    ticketDraft = "Brouillon",
    ticketPending = "En attente",
    ticketInProgress = "En cours",
    ticketReadyToPick = "Prêt à retirer",
    ticketPickedUp = "Retiré",
    ticketCancelled = "Annulé",
    ticketUnknown = "Inconnu",
    itemPendingWash = "En attente",
    itemWashing = "En cours",
    itemDone = "Terminé",
    itemReadyToPick = "Prêt à retirer",
    typeCloth = "Vêtement",
    typeCar = "Véhicule",
    typeShoe = "Chaussures",
    typeCarpet = "Tapis",
    priorityCritical = "Critique",
    priorityUrgent = "Express",
    priorityNormal = "Normal",
    devicePrinter = "Imprimante",
    deviceScanner = "Scanner",
    deviceCashDrawer = "Tiroir-caisse",
    moreNeedsNetwork = "%s demande une connexion. Les clients, le catalogue et les bons en cache restent disponibles sur cette caisse.",
    workspaceTitle = "Accueil",
    workspaceOnlineHint = "Cette caisse est en ligne ; l'état est vérifié en direct.",
    workspaceOfflineHint = "Cette caisse est hors ligne et utilise ses données en cache.",
    metricCatalog = "Catalogue",
    metricPendingOrders = "En attente de synchro",
    metricFailedOrders = "Rejetées",
    cashSectionTitle = "Caisse espèces",
    cashReadyOffline = "Le service et le tiroir sont prêts ; les espèces peuvent être encaissées hors ligne.",
    cashCheckedOnline = "Le service et le tiroir sont vérifiés en direct à l'ouverture de la caisse.",
    cashNeedsSync = "Rétablissez le réseau et synchronisez le service et le tiroir pour encaisser hors ligne.",
    openTill = "Ouvrir la caisse",
    synchronizing = "Synchronisation…",
    intakeTitle = "Accueil client",
    intakeOnlineHint = "Recherchez un client, puis créez un bon de service.",
    intakeOfflineHint = "Hors ligne vous pouvez chercher les clients en cache ; créer un client ou un bon demande une connexion.",
    newCustomer = "＋ Nouveau client",
    newCustomerShort = "Nouveau client",
    lookupTitle = "Rechercher un client",
    lookupHint = "Saisissez un nom, un numéro de téléphone ou un compte.",
    lookupLabel = "Nom, téléphone ou compte",
    lookupPlaceholder = "Par exemple : Awa Diop / 77 000 0000",
    search = "Rechercher",
    customerRecord = "Fiche client",
    change = "Changer",
    contactDetails = "Contact",
    noContactDetails = "Aucun téléphone ni e-mail enregistré",
    customerStatusActive = "Statut : actif",
    customerStatusPrefix = "Statut : %s",
    recentWork = "Travaux récents",
    newestFirst = "Les plus récents d'abord",
    noCachedTickets = "Aucune commande de service en cache. La première que vous créez apparaîtra ici.",
    newOrder = "＋ Nouvelle commande",
    intakeEmptyTitle = "Lancez une recherche",
    intakeEmptyDescription = "La liste complète des clients n'est pas affichée par défaut. Cherchez par nom, téléphone ou compte.",
    intakeNoMatchTitle = "Aucun client trouvé",
    intakeNoMatchDescription = "Aucun client en cache ne correspond à « %s ». Vérifiez les informations ou créez un client.",
    matchingCustomers = "Clients correspondants",
    matchingCustomersCount = "%d résultat sur cette caisse. Touchez-en un pour créer un bon.",
    noPhoneOnFile = "Aucun téléphone enregistré",
    select = "Choisir",
    serviceOrder = "Commande de service",
    itemsCountSuffix = "%d articles",
    expectedPickup = "Retrait : %s",
    continueProcessing = "Continuer ›",
    ticketsTitle = "Bons",
    ticketsEmpty = "Aucun bon synchronisé sur cette caisse.",
    serviceTicket = "Bon de service",
    syncLocalData = "Synchroniser cette caisse",
    backToMore = "Retour à Plus",
    refreshing = "Actualisation…",
    refreshStatus = "Actualiser l'état",
    shiftTitle = "Service et caisse",
    shiftIntro = "Le service, la caisse et le comptage sont enregistrés séparément. Pointez, puis ouvrez la caisse pour encaisser en sécurité.",
    shiftOfflineNotice = "Hors ligne : vous pouvez continuer à vendre les produits en cache, mais le service, la caisse et les mouvements d'espèces demandent une connexion.",
    shiftLoading = "Chargement de l'état du service et de la caisse",
    shiftLoadFailed = "Si le chargement échoue, vérifiez la connexion puis touchez « Actualiser l'état ».",
    reload = "Recharger",
    staffShift = "Service du personnel",
    shiftOpen = "Pointé. Vous pouvez prendre une pause ou continuer à vendre.",
    shiftOnBreak = "En pause. Terminez la pause avant de vendre à nouveau.",
    shiftClosed = "Non pointé. Pointez pour que les ventes en espèces soient rattachées à ce service.",
    clockingIn = "Pointage en cours…",
    clockIn = "Pointer l'arrivée",
    breakStarting = "Démarrage…",
    breakStart = "Commencer la pause",
    clockOut = "Pointer la sortie",
    breakEnding = "Fin de pause…",
    breakEnd = "Terminer la pause",
    registerTitle = "Caisse",
    cashModeNone = "Les espèces ne sont pas activées sur cette caisse. Vous pouvez consulter l'état mais pas encaisser.",
    cashModeUntracked = "Cette caisse accepte les espèces, mais le magasin ne suit pas le montant du tiroir.",
    cashModePersonal = "Cette caisse utilise le fonds personnel ; chaque employé ouvre sa propre session.",
    cashModeShared = "Cette caisse utilise un tiroir partagé. Une fois ouvert, vous pouvez enregistrer le fonds, les entrées et les sorties.",
    openingFloatRequired = "Fonds d'ouverture *",
    openingFloatOptional = "Fonds d'ouverture (facultatif)",
    openingFloatNeeded = "Ce magasin exige un fonds d'ouverture avant d'ouvrir la caisse.",
    registerOpening = "Ouverture…",
    openMyCashSession = "Ouvrir ma session",
    openRegister = "Ouvrir la caisse",
    registerStatus = "État de la caisse",
    thisTerminal = "Cette caisse",
    opened = "Ouverte",
    notOpened = "Fermée",
    cashSession = "Session de caisse",
    myPersonalCash = "Mon fonds personnel",
    sharedDrawer = "Tiroir partagé",
    expectedCash = "Espèces attendues",
    thisRegister = "Cette caisse",
    netSales = "Ventes nettes",
    outstandingOrders = "Commandes impayées",
    awaitingProcessing = "En attente de traitement",
    cashInOut = "Entrée / sortie d'espèces",
    amountLabel = "Montant",
    reasonLabel = "Motif (3 caractères minimum)",
    recording = "Enregistrement…",
    payIn = "Entrée d'espèces",
    payOut = "Sortie d'espèces",
    countAndCloseMyCash = "Compter et clôturer mon fonds",
    closeRegisterZReport = "Clôturer la caisse et imprimer un rapport Z",
    closeRegisterHint = "La clôture crée ou met à jour cet enregistrement de passation. Confirmez le montant compté.",
    countedCashRequired = "Espèces comptées *",
    countedCashOptional = "Espèces comptées (facultatif)",
    handoverNotes = "Notes de passation (facultatif)",
    countedCashNeeded = "Ce magasin exige un montant compté avant la clôture.",
    closing = "Clôture…",
    confirmClose = "Confirmer la clôture",
    notYet = "Pas maintenant",
    closeNeedsManager = "Chaque employé ouvre et clôture sa propre session ; seul un propriétaire ou un responsable clôture la caisse.",
    recentZReports = "Rapports Z récents",
    varianceLabel = "Écart",
    localData = "Données de cette caisse",
    cachedSummary = "%d produits en cache ; %d commandes espèces en attente de synchro.",
    confirmClockOutTitle = "Pointer la sortie ?",
    confirmClockOutBody = "Vous devrez saisir votre PIN et pointer de nouveau avant de vendre.",
    checkAgain = "Je vérifie",
    confirmClockOut = "Pointer la sortie",
    readyOnlineCash = "Prêt pour les espèces en ligne",
    readyOfflineCash = "Prêt pour les espèces hors ligne",
    cashDisabledStore = "Les espèces ne sont pas activées pour ce magasin. Un administrateur doit les activer dans les réglages POS, puis resynchroniser.",
    cashNeedsShiftOnline = "Une commande espèces exige un service ouvert et un tiroir ouvert.",
    cashNeedsShiftOffline = "Une commande espèces hors ligne doit être rattachée à un service et un tiroir ouverts, afin que les espèces encaissées sans réseau restent attribuées.",
    startMyShift = "Commencer mon service",
    shiftStarted = "Service commencé.",
    drawerOpeningCash = "Espèces d'ouverture",
    openDrawerAndSync = "Ouvrir le tiroir et synchroniser",
    openTicket = "Ouvrir le bon",

)

/** Copy for the terminal's selected language, falling back to Chinese. */
internal fun nativePosCopy(languageCode: String?): NativePosCopy =
    when (languageCode?.trim()?.lowercase()) {
        "en" -> COPY_EN
        "fr" -> COPY_FR
        else -> COPY_ZH
    }
