package com.cleanhub.pos.nativepos

/**
 * Cashier-facing copy for the native POS.
 *
 * The app was written in Chinese throughout, with a three-language picker that
 * reached only the PIN screen -- so a French cashier signed in through French
 * copy and then met Chinese for everything after it. Tenants already run in
 * French, so this is not hypothetical.
 *
 * This covers the checkout path a cashier meets during every sale: the till
 * itself, payment, receipts, hardware faults and the errors those raise.
 * Lower-traffic screens (settings, shift reports, the More tab) are still
 * Chinese-only and are listed in the review; they are reached by a manager who
 * can be trained, not by a cashier under queue pressure.
 *
 * Kotlin has no resource-bundle equivalent that works for this shape without
 * dragging in Android resources, and Android string resources cannot be
 * switched per terminal at runtime without recreating the Activity. A data
 * class keeps every language complete by construction: add a field and the
 * compiler names the three places to fill in.
 */
internal data class NativePosCopy(
    // --- status and connectivity ---
    val online: String,
    val offline: String,
    val offlineMode: String,
    val syncing: String,
    val synchronize: String,
    val pendingSalesSuffix: String,

    // --- sale screen ---
    val catalogTitle: String,
    val cartEmpty: String,
    val amountDue: String,
    val checkout: String,
    val cashTendered: String,
    val changeDue: String,
    val subtotal: String,
    val tax: String,
    val rounding: String,
    val total: String,

    // --- receipt delivery ---
    val receiptPrint: String,
    val receiptNone: String,
    val receiptQueued: String,

    // --- outcomes ---
    val saleSubmittedOnline: String,
    val saleQueuedOffline: String,
    val cashPaymentRecorded: String,

    // --- refusals the cashier can act on ---
    val tenderBelowTotal: String,
    val cartIsEmpty: String,
    val priceChanged: String,
    val shiftAndDrawerRequired: String,
    val requiresNetwork: String,
    val networkError: String,
    val genericFailure: String,
    val staleCatalogWarning: String,

    // --- hardware ---
    val printerNotConnected: String,
    val printerOutOfPaper: String,
    val printerCoverOpen: String,
    val printerOverheated: String,
    val drawerOpened: String,
    val drawerDisconnected: String,

    // --- bottom navigation and the More menu ---
    val tabWorkspace: String,
    val tabSale: String,
    val tabIntake: String,
    val tabTickets: String,
    val tabMore: String,
    val menuMore: String,
    val menuCustomers: String,
    val menuCatalog: String,
    val menuScan: String,
    val menuOrders: String,
    val menuOrderDetail: String,
    val menuStatistics: String,
    val menuNotifications: String,
    val menuShift: String,
    val menuSettings: String,
    val menuHardware: String,

    // --- ticket status, as the server names it ---
    val ticketDraft: String,
    val ticketPending: String,
    val ticketInProgress: String,
    val ticketReadyToPick: String,
    val ticketPickedUp: String,
    val ticketCancelled: String,
    val ticketUnknown: String,
    val itemPendingWash: String,
    val itemWashing: String,
    val itemDone: String,
    val itemReadyToPick: String,

    // --- ticket item types and priority ---
    val typeCloth: String,
    val typeCar: String,
    val typeShoe: String,
    val typeCarpet: String,
    val priorityCritical: String,
    val priorityUrgent: String,
    val priorityNormal: String,

    // --- hardware device types ---
    val devicePrinter: String,
    val deviceScanner: String,
    val deviceCashDrawer: String,

    // --- workspace, intake and ticket list ---
    val moreNeedsNetwork: String,
    val workspaceTitle: String,
    val workspaceOnlineHint: String,
    val workspaceOfflineHint: String,
    val metricCatalog: String,
    val metricPendingOrders: String,
    val metricFailedOrders: String,
    val cashSectionTitle: String,
    val cashReadyOffline: String,
    val cashCheckedOnline: String,
    val cashNeedsSync: String,
    val openTill: String,
    val synchronizing: String,
    val intakeTitle: String,
    val intakeOnlineHint: String,
    val intakeOfflineHint: String,
    val newCustomer: String,
    val newCustomerShort: String,
    val lookupTitle: String,
    val lookupHint: String,
    val lookupLabel: String,
    val lookupPlaceholder: String,
    val search: String,
    val customerRecord: String,
    val change: String,
    val contactDetails: String,
    val noContactDetails: String,
    val customerStatusActive: String,
    val customerStatusPrefix: String,
    val recentWork: String,
    val newestFirst: String,
    val noCachedTickets: String,
    val newOrder: String,
    val intakeEmptyTitle: String,
    val intakeEmptyDescription: String,
    val intakeNoMatchTitle: String,
    val intakeNoMatchDescription: String,
    val matchingCustomers: String,
    val matchingCustomersCount: String,
    val noPhoneOnFile: String,
    val select: String,
    val serviceOrder: String,
    val itemsCountSuffix: String,
    val expectedPickup: String,
    val continueProcessing: String,
    val ticketsTitle: String,
    val ticketsEmpty: String,
    val serviceTicket: String,
    val syncLocalData: String,

    // --- shift, register and cash movements ---
    val backToMore: String,
    val refreshing: String,
    val refreshStatus: String,
    val shiftTitle: String,
    val shiftIntro: String,
    val shiftOfflineNotice: String,
    val shiftLoading: String,
    val shiftLoadFailed: String,
    val reload: String,
    val staffShift: String,
    val shiftOpen: String,
    val shiftOnBreak: String,
    val shiftClosed: String,
    val clockingIn: String,
    val clockIn: String,
    val breakStarting: String,
    val breakStart: String,
    val clockOut: String,
    val breakEnding: String,
    val breakEnd: String,
    val registerTitle: String,
    val cashModeNone: String,
    val cashModeUntracked: String,
    val cashModePersonal: String,
    val cashModeShared: String,
    val openingFloatRequired: String,
    val openingFloatOptional: String,
    val openingFloatNeeded: String,
    val registerOpening: String,
    val openMyCashSession: String,
    val openRegister: String,
    val registerStatus: String,
    val thisTerminal: String,
    val opened: String,
    val notOpened: String,
    val cashSession: String,
    val myPersonalCash: String,
    val sharedDrawer: String,
    val expectedCash: String,
    val thisRegister: String,
    val netSales: String,
    val outstandingOrders: String,
    val awaitingProcessing: String,
    val cashInOut: String,
    val amountLabel: String,
    val reasonLabel: String,
    val recording: String,
    val payIn: String,
    val payOut: String,
    val countAndCloseMyCash: String,
    val closeRegisterZReport: String,
    val closeRegisterHint: String,
    val countedCashRequired: String,
    val countedCashOptional: String,
    val handoverNotes: String,
    val countedCashNeeded: String,
    val closing: String,
    val confirmClose: String,
    val notYet: String,
    val closeNeedsManager: String,
    val recentZReports: String,
    val varianceLabel: String,
    val localData: String,
    val cachedSummary: String,
    val confirmClockOutTitle: String,
    val confirmClockOutBody: String,
    val checkAgain: String,
    val confirmClockOut: String,
    val readyOnlineCash: String,
    val readyOfflineCash: String,
    val cashDisabledStore: String,
    val cashNeedsShiftOnline: String,
    val cashNeedsShiftOffline: String,
    val startMyShift: String,
    val shiftStarted: String,
    val drawerOpeningCash: String,
    val openDrawerAndSync: String,

    // --- ticket detail, items and the intake dialogs ---
    val newCustomerTitle: String,
    val newCustomerHint: String,
    val back: String,
    val customerInfo: String,
    val customerName: String,
    val customerNamePlaceholder: String,
    val phoneNumber: String,
    val phonePlaceholder: String,
    val saving: String,
    val saveCustomer: String,
    val newTicketTitle: String,
    val newTicketHint: String,
    val ticketCustomer: String,
    val ticketType: String,
    val typeLaundry: String,
    val typeCarWash: String,
    val priorityTitle: String,
    val expectedPickupField: String,
    val remarkOptional: String,
    val remarkPlaceholder: String,
    val ticketNeedsNetwork: String,
    val creating: String,
    val createTicket: String,
    val backToTickets: String,
    val serviceItemsCount: String,
    val ticketOfflineNotice: String,
    val ticketFlow: String,
    val cancelReasonRequired: String,
    val confirmPickedUp: String,
    val updateToStatus: String,
    val serviceItems: String,
    val noServiceItems: String,
    val alreadyBilled: String,
    val pendingSyncNoBill: String,
    val appendServiceItem: String,
    val noCachedServices: String,
    val noServicesForType: String,
    val pendingService: String,
    val itemTypePrefix: String,
    val changeItemType: String,
    val weightKg: String,
    val bagCount: String,
    val quantityPieces: String,
    val categoryOptional: String,
    val colorOptional: String,
    val brandOptional: String,
    val materialOptional: String,
    val defectsOptional: String,
    val specialRequestOptional: String,
    val itemNoteOptional: String,
    val adding: String,
    val confirmAddItem: String,
    val pickTypeThenService: String,
    val pickedTypeNowService: String,
    val addToCartTitle: String,
    val addToCartHint: String,
    val linkedToOrder: String,
    val awaitingSync: String,
    val inCart: String,
    val selected: String,
    val notSelected: String,
    val somePaymentsQueued: String,
    val addingTotalHint: String,
    val addingToCart: String,
    val nothingToCharge: String,
    val bagsSuffix: String,
    val piecesSuffix: String,
    val defectsPrefix: String,
    val specialRequestPrefix: String,
    val notePrefix: String,
    val editItem: String,
    val deleteItem: String,
    val deleteReasonRequired: String,
    val confirmDeleteItem: String,
    val editServiceItem: String,
    val editServiceItemHint: String,
    val saveItem: String,
    val cancelEdit: String,

    // --- the More section: customers, catalogue, scan, orders, figures, settings, hardware ---
    val scanLabel: String,
    val productsServices: String,
    val statisticsShort: String,
    val settingsShort: String,
    val customersCachedHint: String,
    val nameAccountOrPhone: String,
    val newServiceTicket: String,
    val customerRegistration: String,
    val createCustomer: String,
    val noCachedMatches: String,
    val noContactOnFile: String,
    val tapToStartIntake: String,
    val productsHeading: String,
    val syncedSellOffline: String,
    val usingLocalCatalog: String,
    val addToTillList: String,
    val servicePrices: String,
    val scanIntro: String,
    val scanOrType: String,
    val searching: String,
    val searchOnline: String,
    val startBuiltInScanner: String,
    val scanEmptyHint: String,
    val ticketPrefix: String,
    val productAddToTill: String,
    val customerPrefix: String,
    val onlineSearchResults: String,
    val noMatchFound: String,
    val archiveNotification: String,
    val loading: String,
    val refreshOrders: String,
    val noOrdersToShow: String,
    val orderPrefix: String,
    val walkInCustomer: String,
    val tapToProcessOrder: String,
    val openOrderWhenOnline: String,
    val customerLabel: String,
    val orderStatus: String,
    val orderAmount: String,
    val paidPrefix: String,
    val cashCollection: String,
    val outstandingHint: String,
    val tenderedForChange: String,
    val chargeOutstanding: String,
    val defaultChargeOutstanding: String,
    val enterTenderAndChange: String,
    val confirmTakeCash: String,
    val orderProcessing: String,
    val confirmReceived: String,
    val confirmDelivered: String,
    val orderItems: String,
    val quantityPrefix: String,
    val paymentRecords: String,
    val periodToday: String,
    val periodWeek: String,
    val periodMonth: String,
    val periodAll: String,
    val refreshData: String,
    val ordersLabel: String,
    val ordersSummary: String,
    val ticketsLabel: String,
    val ticketsSummary: String,
    val customersSummary: String,
    val statisticsWhenOnline: String,
    val refreshNotifications: String,
    val noNotifications: String,
    val archive: String,
    val refreshTerminalSettings: String,
    val terminalLabel: String,
    val printerDrawerScanner: String,
    val hardwareSettingsHint: String,
    val openHardwareSettings: String,
    val cashHandlingMode: String,
    val terminalPreferences: String,
    val terminalName: String,
    val autoLockSeconds: String,
    val autoPrintCopies: String,
    val copiesSuffix: String,
    val receiptPrinting: String,
    val autoPrintOption: String,
    val manualPrintOption: String,
    val cashRounding: String,
    val roundingNone: String,
    val roundingJiao: String,
    val roundingYuan: String,
    val saveTerminalSettings: String,
    val syncStatus: String,
    val settingsWhenOnline: String,
    val hardwareIntro: String,
    val detecting: String,
    val refreshHardware: String,
    val readingHardware: String,
    val hardwareModel: String,
    val builtInPrinter: String,
    val noBuiltInPrinter: String,
    val statusLabel: String,
    val connected: String,
    val notConnected: String,
    val printTestPage: String,
    val testAndRegister: String,
    val builtInScanner: String,
    val noBuiltInScanner: String,
    val connectedReadyToScan: String,
    val startScanTest: String,
    val drawerTitle: String,
    val drawerConnectedHint: String,
    val drawerUnavailable: String,
    val authoriseAndTestDrawer: String,
    val hardwareManagerOnly: String,
    val registeredDevices: String,
    val noRegisteredDevicesOnline: String,
    val noRegisteredDevicesOffline: String,
    val defaultReceiptPrinter: String,
    val deviceEnabled: String,
    val deviceDisabled: String,
    val bluetoothPrinter: String,
    val bluetoothIntro: String,
    val authoriseBluetooth: String,
    val readPairedDevices: String,
    val noPairedPrinters: String,
    val paired: String,
    val testAndBindTo: String,
    val needRegisteredPrinter: String,
    val localReceiptQueue: String,
    val receiptQueueSummary: String,
    val printNextReceipt: String,
    val useDefaultPrinterHint: String,
    val openTicket: String,
)

private val COPY_ZH = NativePosCopy(
    online = "已联网",
    offline = "离线",
    offlineMode = "离线模式",
    syncing = "同步中",
    synchronize = "同步",
    pendingSalesSuffix = "待同步 %d 笔",
    catalogTitle = "商品目录",
    cartEmpty = "购物车为空。",
    amountDue = "应收金额",
    checkout = "结算",
    cashTendered = "实收现金",
    changeDue = "应找零",
    subtotal = "小计",
    tax = "税费",
    rounding = "抹零",
    total = "合计",
    receiptPrint = "打印小票",
    receiptNone = "不打小票",
    receiptQueued = "收据已加入本地打印队列。",
    saleSubmittedOnline = "现金订单已提交；如网络在响应中断开，将使用同一订单号安全补传。",
    saleQueuedOffline = "现金订单已写入本地队列；联网后将使用同一订单号安全同步。",
    cashPaymentRecorded = "现金收款已记录。",
    tenderBelowTotal = "实收金额不能少于应收金额。",
    cartIsEmpty = "购物车为空。",
    priceChanged = "价格、优惠或税费已更新，请重新确认结款。",
    shiftAndDrawerRequired = "现金收款需要已开始的班次和已打开的钱箱。",
    requiresNetwork = "该操作需要联网；恢复网络后即可继续。",
    networkError = "网络错误，请检查本机网络后重试。",
    genericFailure = "操作未完成：请检查网络或稍后重试。",
    staleCatalogWarning = "本机商品与价格已有 %d 小时未更新，请尽快同步后再继续销售。",
    printerNotConnected = "打印机未连接。",
    printerOutOfPaper = "打印机缺纸，请装入热敏纸后重试。",
    printerCoverOpen = "打印机仓盖未关闭。",
    printerOverheated = "打印机温度过高，请稍后重试。",
    drawerOpened = "钱箱已打开。",
    drawerDisconnected = "钱箱服务已断开，请刷新硬件状态后重试。",
    tabWorkspace = "工作台",
    tabSale = "收银",
    tabIntake = "开单",
    tabTickets = "工单",
    tabMore = "更多",
    menuMore = "更多",
    menuCustomers = "客户管理",
    menuCatalog = "商品与服务目录",
    menuScan = "扫码查询",
    menuOrders = "订单管理",
    menuOrderDetail = "订单详情",
    menuStatistics = "经营数据",
    menuNotifications = "通知中心",
    menuShift = "班次与收银",
    menuSettings = "终端设置",
    menuHardware = "打印与硬件",
    ticketDraft = "草稿",
    ticketPending = "待处理",
    ticketInProgress = "处理中",
    ticketReadyToPick = "待取件",
    ticketPickedUp = "已取件",
    ticketCancelled = "已取消",
    ticketUnknown = "异常",
    itemPendingWash = "待处理",
    itemWashing = "处理中",
    itemDone = "已完成",
    itemReadyToPick = "待取件",
    typeCloth = "衣物",
    typeCar = "车辆",
    typeShoe = "鞋类",
    typeCarpet = "地毯",
    priorityCritical = "紧急",
    priorityUrgent = "加急",
    priorityNormal = "普通",
    devicePrinter = "打印机",
    deviceScanner = "扫码器",
    deviceCashDrawer = "钱箱",
    moreNeedsNetwork = "%s 需要联网加载；当前仍可使用本机缓存的客户、目录和工单。",
    workspaceTitle = "工作台",
    workspaceOnlineHint = "设备已联网，可实时核验收银状态",
    workspaceOfflineHint = "设备离线，使用本机已缓存的收银数据",
    metricCatalog = "商品目录",
    metricPendingOrders = "待同步订单",
    metricFailedOrders = "异常订单",
    cashSectionTitle = "现金收银",
    cashReadyOffline = "班次和钱箱已就绪，可以安全离线收取现金。",
    cashCheckedOnline = "进入收银后会实时核验班次和钱箱状态。",
    cashNeedsSync = "恢复网络并同步班次和钱箱后，即可继续离线收银。",
    openTill = "进入收银",
    synchronizing = "正在同步…",
    intakeTitle = "客户接待",
    intakeOnlineHint = "查询客户档案，选择客户后创建服务工单。",
    intakeOfflineHint = "离线时可查询已缓存客户；创建客户和工单需要联网。",
    newCustomer = "＋ 新建客户",
    newCustomerShort = "新建客户",
    lookupTitle = "查询客户档案",
    lookupHint = "输入客户姓名、手机号或账户名称。",
    lookupLabel = "姓名、电话或账户",
    lookupPlaceholder = "例如：Awa Diop / 77 000 0000",
    search = "查询",
    customerRecord = "客户档案",
    change = "更换",
    contactDetails = "联系方式",
    noContactDetails = "未填写联系电话或邮箱",
    customerStatusActive = "客户状态：正常",
    customerStatusPrefix = "客户状态：%s",
    recentWork = "最近处理",
    newestFirst = "最新在上",
    noCachedTickets = "暂无已缓存的服务订单。创建第一笔订单后会显示在这里。",
    newOrder = "＋ 新增订单",
    intakeEmptyTitle = "输入客户信息开始查询",
    intakeEmptyDescription = "默认不会展示全部客户资料。请输入姓名、手机号或账户名称查找客户。",
    intakeNoMatchTitle = "未找到客户",
    intakeNoMatchDescription = "没有与“%s”匹配的已缓存客户。请核对信息或新建客户。",
    matchingCustomers = "匹配客户",
    matchingCustomersCount = "%d 条本机匹配结果，点击后继续开单。",
    noPhoneOnFile = "未填写手机号",
    select = "选择",
    serviceOrder = "服务订单",
    itemsCountSuffix = "%d 项",
    expectedPickup = "预计取件：%s",
    continueProcessing = "继续处理 ›",
    ticketsTitle = "工单",
    ticketsEmpty = "本机暂时没有已同步工单。",
    serviceTicket = "服务工单",
    syncLocalData = "同步本机数据",
    backToMore = "返回更多",
    refreshing = "正在刷新…",
    refreshStatus = "刷新状态",
    shiftTitle = "班次与收银",
    shiftIntro = "班次、收银台和现金盘点分别记录；开始班次后，再开启收银台即可安全进行现金收款。",
    shiftOfflineNotice = "当前离线：可继续销售已缓存商品，但班次、收银台和现金流水必须恢复联网后操作。",
    shiftLoading = "正在读取班次与收银台状态",
    shiftLoadFailed = "若加载失败，请确认设备联网后点击“刷新状态”。",
    reload = "重新加载",
    staffShift = "员工班次",
    shiftOpen = "当前上班中。可以开始休息，或继续收银。",
    shiftOnBreak = "当前处于休息中。结束休息后才能继续收银。",
    shiftClosed = "当前未开始班次。开始班次后，现金销售才能关联到本次交接。",
    clockingIn = "正在开始班次…",
    clockIn = "开始班次",
    breakStarting = "正在开始…",
    breakStart = "开始休息",
    clockOut = "结束班次",
    breakEnding = "正在结束休息…",
    breakEnd = "结束休息",
    registerTitle = "收银台",
    cashModeNone = "此终端未启用现金收款。可以查看收银台状态，但不能收取现金。",
    cashModeUntracked = "本终端接受现金，但门店不跟踪钱箱金额。",
    cashModePersonal = "本终端使用员工随身现金；每位员工需要开启自己的现金会话。",
    cashModeShared = "本终端使用共享钱箱；开启后可记录备用金、现金存入和现金支出。",
    openingFloatRequired = "开柜备用金 *",
    openingFloatOptional = "开柜备用金（可选）",
    openingFloatNeeded = "此门店要求填写开柜备用金后才能开启收银台。",
    registerOpening = "正在开启…",
    openMyCashSession = "开启我的现金会话",
    openRegister = "开启收银台",
    registerStatus = "收银台状态",
    thisTerminal = "本终端",
    opened = "已开启",
    notOpened = "未开启",
    cashSession = "现金会话",
    myPersonalCash = "我的随身现金",
    sharedDrawer = "共享钱箱",
    expectedCash = "系统应有现金",
    thisRegister = "本次收银台",
    netSales = "净销售额",
    outstandingOrders = "待收订单",
    awaitingProcessing = "等待处理",
    cashInOut = "现金存入 / 支出",
    amountLabel = "金额",
    reasonLabel = "原因（至少 3 个字）",
    recording = "正在记录…",
    payIn = "现金存入",
    payOut = "现金支出",
    countAndCloseMyCash = "盘点并关闭我的现金",
    closeRegisterZReport = "关闭收银台并生成 Z Report",
    closeRegisterHint = "关闭后会生成或更新本次交接记录。请确认实点金额。",
    countedCashRequired = "实点现金 *",
    countedCashOptional = "实点现金（可选）",
    handoverNotes = "交接备注（可选）",
    countedCashNeeded = "此门店要求填写实点现金后才能关闭。",
    closing = "正在关闭…",
    confirmClose = "确认关闭",
    notYet = "暂不关闭",
    closeNeedsManager = "请先由当前员工开启或关闭自己的现金会话；只有店主或经理可以最终关闭收银台。",
    recentZReports = "最近 Z Report",
    varianceLabel = "差额",
    localData = "本机数据",
    cachedSummary = "已缓存 %d 个商品；%d 笔现金订单等待同步。",
    confirmClockOutTitle = "确认结束班次？",
    confirmClockOutBody = "结束后需要重新输入 PIN 并开始班次，才能继续收银。",
    checkAgain = "再检查一下",
    confirmClockOut = "确认结束",
    readyOnlineCash = "准备在线现金收银",
    readyOfflineCash = "准备离线现金收银",
    cashDisabledStore = "此门店当前没有启用现金收款。请由管理员在门店 POS 设置中启用现金支付后重新同步。",
    cashNeedsShiftOnline = "现金订单需要关联已开始的班次和已打开的钱箱。",
    cashNeedsShiftOffline = "离线现金订单必须关联已开始的班次和已打开的钱箱，避免断网时的现金记录失去归属。",
    startMyShift = "开始我的班次",
    shiftStarted = "班次已开始。",
    drawerOpeningCash = "开箱现金",
    openDrawerAndSync = "打开钱箱并同步",
    newCustomerTitle = "新建客户",
    newCustomerHint = "先建立客户账户，随后可立即创建服务工单。",
    back = "返回",
    customerInfo = "客户信息",
    customerName = "客户姓名",
    customerNamePlaceholder = "例如：Awa Diop",
    phoneNumber = "手机号码",
    phonePlaceholder = "例如：77 000 0000",
    saving = "正在保存…",
    saveCustomer = "保存客户",
    newTicketTitle = "新建服务工单",
    newTicketHint = "项目与价格将在下一步录入。",
    ticketCustomer = "服务客户",
    ticketType = "工单类型",
    typeLaundry = "洗衣护理",
    typeCarWash = "车辆清洗",
    priorityTitle = "优先级",
    expectedPickupField = "预计取件时间（可选）",
    remarkOptional = "备注（可选）",
    remarkPlaceholder = "通用服务备注",
    ticketNeedsNetwork = "创建工单需要联网；恢复网络后即可继续。",
    creating = "正在创建…",
    createTicket = "创建工单",
    backToTickets = "返回工单列表",
    serviceItemsCount = "%d 个服务项目",
    ticketOfflineNotice = "离线模式：可查看已缓存的项目和收款队列；项目处理与取件需恢复网络。",
    ticketFlow = "工单流转",
    cancelReasonRequired = "取消原因（选择取消时必填）",
    confirmPickedUp = "确认客户已取件（需校验结算）",
    updateToStatus = "更新为“%s”",
    serviceItems = "服务项目",
    noServiceItems = "此工单尚未添加服务项目。",
    alreadyBilled = "已加入订单，不能重复结算",
    pendingSyncNoBill = "本机收款待同步，不能重复结算",
    appendServiceItem = "追加服务项目",
    noCachedServices = "没有已缓存的服务项目，请先同步。",
    noServicesForType = "当前工单类型没有可追加的服务项目，请先在后台配置服务目录。",
    pendingService = "待追加服务",
    itemTypePrefix = "物品类型：%s",
    changeItemType = "更换物品类型",
    weightKg = "重量（kg）",
    bagCount = "袋数",
    quantityPieces = "数量（件）",
    categoryOptional = "分类（可选）",
    colorOptional = "颜色（可选）",
    brandOptional = "品牌（可选）",
    materialOptional = "材质（可选）",
    defectsOptional = "瑕疵（可选）",
    specialRequestOptional = "特殊要求（可选）",
    itemNoteOptional = "项目备注（可选）",
    adding = "正在添加…",
    confirmAddItem = "确认添加项目",
    pickTypeThenService = "先选择物品类型，再选择可提供该服务的价目。",
    pickedTypeNowService = "已选择“%s”，请选择适用服务。",
    addToCartTitle = "加入收银购物车",
    addToCartHint = "选择本次要结算的项目。已加入订单、待同步项目和当前购物车项目会自动排除。",
    linkedToOrder = "已关联订单",
    awaitingSync = "等待同步",
    inCart = "已在购物车",
    selected = "已选择",
    notSelected = "未选择",
    somePaymentsQueued = "部分项目的现金收款仍在本机队列中；其余未结算项目可以单独收款。",
    addingTotalHint = "本次加入 %s；可与零售商品或同一客户的其他工单一起现金结算。",
    addingToCart = "正在加入…",
    nothingToCharge = "没有可在本次结算的项目。",
    bagsSuffix = "%s 袋",
    piecesSuffix = "%s 件",
    defectsPrefix = "瑕疵：%s",
    specialRequestPrefix = "特殊要求：%s",
    notePrefix = "备注：%s",
    editItem = "编辑项目",
    deleteItem = "删除项目",
    deleteReasonRequired = "删除原因（必填）",
    confirmDeleteItem = "确认删除项目",
    editServiceItem = "编辑服务项目",
    editServiceItemHint = "先选物品类型，再选择该类型可用的服务。收费单价和改价权限仍由后台规则校验。",
    saveItem = "保存项目",
    cancelEdit = "取消编辑",
    scanLabel = "扫描标签",
    productsServices = "产品服务",
    statisticsShort = "统计数据",
    settingsShort = "设置",
    customersCachedHint = "客户档案保存在本机；联网时新建客户会立即同步。",
    nameAccountOrPhone = "姓名、账户或手机号",
    newServiceTicket = "新建服务工单",
    customerRegistration = "客户建档",
    createCustomer = "创建客户",
    noCachedMatches = "没有匹配的已缓存客户。",
    noContactOnFile = "未填写联系方式",
    tapToStartIntake = "点击后直接带入服务开单",
    productsHeading = "商品",
    syncedSellOffline = "已同步，可离线销售",
    usingLocalCatalog = "使用本地商品目录",
    addToTillList = "加入收银清单",
    servicePrices = "服务价目",
    scanIntro = "支持内置扫码器、扫码枪键盘输入，也可手动输入工单号、订单号、手机号或客户名。联网时会调用和 POS Web 相同的全局检索。",
    scanOrType = "扫描或输入关键词",
    searching = "正在查询…",
    searchOnline = "联网查询",
    startBuiltInScanner = "启动内置扫码器",
    scanEmptyHint = "输入后可查询本机缓存，也可联网查询完整订单、工单和客户。",
    ticketPrefix = "工单 %s",
    productAddToTill = "商品 %s · 加入收银",
    customerPrefix = "客户 %s",
    onlineSearchResults = "联网查询结果",
    noMatchFound = "未找到已缓存记录；可点击联网查询。",
    archiveNotification = "归档通知",
    loading = "正在加载…",
    refreshOrders = "刷新订单",
    noOrdersToShow = "当前没有可显示订单，联网后点击刷新。",
    orderPrefix = "订单 %s",
    walkInCustomer = "散客",
    tapToProcessOrder = "点击处理订单",
    openOrderWhenOnline = "联网后打开一张订单查看详情。",
    customerLabel = "客户",
    orderStatus = "订单状态",
    orderAmount = "订单金额",
    paidPrefix = "已收 %s",
    cashCollection = "现金收款",
    outstandingHint = "待收 %s。线上订单收款会使用当前班次与钱箱。",
    tenderedForChange = "实收现金（用于找零）",
    chargeOutstanding = "按待收金额收款",
    defaultChargeOutstanding = "现金收款将默认按待收金额入账。",
    enterTenderAndChange = "输入实收金额并找零",
    confirmTakeCash = "确认收取现金",
    orderProcessing = "订单处理",
    confirmReceived = "确认接单",
    confirmDelivered = "确认交付",
    orderItems = "订单项目",
    quantityPrefix = "数量 %s",
    paymentRecords = "收款记录",
    periodToday = "今天",
    periodWeek = "本周",
    periodMonth = "本月",
    periodAll = "全部",
    refreshData = "刷新数据",
    ordersLabel = "订单",
    ordersSummary = "%d 笔 · 未结 %d 笔",
    ticketsLabel = "工单",
    ticketsSummary = "%d 张 · 超期 %d 张",
    customersSummary = "%d 位 · 今日新增 %d 位",
    statisticsWhenOnline = "联网后点击刷新加载经营数据。",
    refreshNotifications = "刷新通知",
    noNotifications = "当前没有可显示通知，联网后点击刷新。",
    archive = "归档",
    refreshTerminalSettings = "刷新终端设置",
    terminalLabel = "终端",
    printerDrawerScanner = "打印、钱箱与扫码器",
    hardwareSettingsHint = "查看本机内置设备状态，测试并登记收据打印机与扫码器。",
    openHardwareSettings = "打开硬件设置",
    cashHandlingMode = "收银方式",
    terminalPreferences = "本机终端偏好",
    terminalName = "终端名称",
    autoLockSeconds = "自动锁定秒数",
    autoPrintCopies = "自动打印份数",
    copiesSuffix = "%s 联",
    receiptPrinting = "收据打印",
    autoPrintOption = "自动打印",
    manualPrintOption = "手动打印",
    cashRounding = "现金取整",
    roundingNone = "不取整",
    roundingJiao = "取整到角",
    roundingYuan = "取整到元",
    saveTerminalSettings = "保存终端设置",
    syncStatus = "同步状态",
    settingsWhenOnline = "联网后点击刷新加载终端设置。",
    hardwareIntro = "这里直接读取 Android POS 的原生硬件服务；设备登记会沿用原 POS Web 的终端级配置。",
    detecting = "正在检测…",
    refreshHardware = "刷新硬件状态",
    readingHardware = "正在读取本机硬件状态。",
    hardwareModel = "硬件型号",
    builtInPrinter = "内置收据打印机",
    noBuiltInPrinter = "当前设备未检测到受支持的内置打印机",
    statusLabel = "状态",
    connected = "已连接",
    notConnected = "未连接",
    printTestPage = "打印测试页",
    testAndRegister = "测试并登记",
    builtInScanner = "内置扫码器",
    noBuiltInScanner = "当前设备未检测到受支持的内置扫码器",
    connectedReadyToScan = "已连接，可开始扫描",
    startScanTest = "启动扫码测试",
    drawerTitle = "钱箱",
    drawerConnectedHint = "本机钱箱服务已连接；手动测试会先向服务端申请审计授权。",
    drawerUnavailable = "当前设备没有可用的钱箱服务。",
    authoriseAndTestDrawer = "申请授权并测试开钱箱",
    hardwareManagerOnly = "只有店主或经理可以登记设备、修改默认打印机和手动测试钱箱。",
    registeredDevices = "已登记设备",
    noRegisteredDevicesOnline = "尚未读取到本终端已登记的设备。",
    noRegisteredDevicesOffline = "恢复网络后可读取终端已登记的设备。",
    defaultReceiptPrinter = "默认收据机",
    deviceEnabled = "已启用",
    deviceDisabled = "未启用",
    bluetoothPrinter = "外接蓝牙打印机",
    bluetoothIntro = "先在 Android 系统蓝牙中完成配对，再在这里测试并绑定到后台登记的打印机。",
    authoriseBluetooth = "授权蓝牙",
    readPairedDevices = "读取已配对设备",
    noPairedPrinters = "尚未读取到已配对蓝牙打印机。",
    paired = "已配对",
    testAndBindTo = "测试并绑定到 %s",
    needRegisteredPrinter = "请先在租户后台为当前终端创建并启用一个外接打印机设备。",
    localReceiptQueue = "本地收据队列",
    receiptQueueSummary = "待打印 %d 张；失败 %d 张（为避免重复出纸，失败任务不会自动重试）。",
    printNextReceipt = "打印下一张收据",
    useDefaultPrinterHint = "请使用后台登记的默认收据打印机打印，队列会保留在本机。",
    openTicket = "查看并处理工单",

)

private val COPY_EN = NativePosCopy(
    online = "Online",
    offline = "Offline",
    offlineMode = "Offline mode",
    syncing = "Syncing",
    synchronize = "Sync",
    pendingSalesSuffix = "%d waiting to sync",
    catalogTitle = "Catalogue",
    cartEmpty = "The cart is empty.",
    amountDue = "Amount due",
    checkout = "Checkout",
    cashTendered = "Cash received",
    changeDue = "Change due",
    subtotal = "Subtotal",
    tax = "Tax",
    rounding = "Rounding",
    total = "Total",
    receiptPrint = "Print receipt",
    receiptNone = "No receipt",
    receiptQueued = "The receipt is in this terminal's print queue.",
    saleSubmittedOnline = "Cash order submitted. If the connection drops before the reply arrives, it is resent safely under the same order number.",
    saleQueuedOffline = "Cash order saved to this terminal. It syncs under the same order number once the network returns.",
    cashPaymentRecorded = "Cash payment recorded.",
    tenderBelowTotal = "Cash received cannot be less than the amount due.",
    cartIsEmpty = "The cart is empty.",
    priceChanged = "The price, discount or tax changed. Confirm the payment again.",
    shiftAndDrawerRequired = "Taking cash needs an open shift and an open drawer.",
    requiresNetwork = "This needs a connection. Try again once the network is back.",
    networkError = "Network error. Check this terminal's connection and try again.",
    genericFailure = "That did not finish. Check the network or try again shortly.",
    staleCatalogWarning = "Products and prices on this terminal are %d hours old. Sync before selling further.",
    printerNotConnected = "The printer is not connected.",
    printerOutOfPaper = "The printer is out of paper. Load thermal paper and try again.",
    printerCoverOpen = "The printer cover is open.",
    printerOverheated = "The printer is too hot. Try again shortly.",
    drawerOpened = "Cash drawer opened.",
    drawerDisconnected = "The cash drawer service disconnected. Refresh the hardware status and try again.",
    tabWorkspace = "Home",
    tabSale = "Till",
    tabIntake = "New ticket",
    tabTickets = "Tickets",
    tabMore = "More",
    menuMore = "More",
    menuCustomers = "Customers",
    menuCatalog = "Products and services",
    menuScan = "Scan to look up",
    menuOrders = "Orders",
    menuOrderDetail = "Order detail",
    menuStatistics = "Business figures",
    menuNotifications = "Notifications",
    menuShift = "Shift and cash",
    menuSettings = "Terminal settings",
    menuHardware = "Printing and hardware",
    ticketDraft = "Draft",
    ticketPending = "Waiting",
    ticketInProgress = "In progress",
    ticketReadyToPick = "Ready for pickup",
    ticketPickedUp = "Picked up",
    ticketCancelled = "Cancelled",
    ticketUnknown = "Unknown",
    itemPendingWash = "Waiting",
    itemWashing = "In progress",
    itemDone = "Done",
    itemReadyToPick = "Ready for pickup",
    typeCloth = "Clothing",
    typeCar = "Vehicle",
    typeShoe = "Shoes",
    typeCarpet = "Carpet",
    priorityCritical = "Critical",
    priorityUrgent = "Rush",
    priorityNormal = "Normal",
    devicePrinter = "Printer",
    deviceScanner = "Scanner",
    deviceCashDrawer = "Cash drawer",
    moreNeedsNetwork = "%s needs a connection. Cached customers, catalogue and tickets stay available on this terminal.",
    workspaceTitle = "Home",
    workspaceOnlineHint = "This terminal is online; till status is checked live.",
    workspaceOfflineHint = "This terminal is offline and using its cached till data.",
    metricCatalog = "Catalogue",
    metricPendingOrders = "Waiting to sync",
    metricFailedOrders = "Rejected",
    cashSectionTitle = "Cash till",
    cashReadyOffline = "Shift and drawer are ready; cash can be taken safely offline.",
    cashCheckedOnline = "Shift and drawer are checked live when you open the till.",
    cashNeedsSync = "Restore the network and sync the shift and drawer to take cash offline again.",
    openTill = "Open the till",
    synchronizing = "Syncing…",
    intakeTitle = "Customer intake",
    intakeOnlineHint = "Look up a customer, then create a service ticket.",
    intakeOfflineHint = "Offline you can search cached customers; creating a customer or ticket needs a connection.",
    newCustomer = "＋ New customer",
    newCustomerShort = "New customer",
    lookupTitle = "Find a customer",
    lookupHint = "Enter a name, phone number or account name.",
    lookupLabel = "Name, phone or account",
    lookupPlaceholder = "For example: Awa Diop / 77 000 0000",
    search = "Search",
    customerRecord = "Customer record",
    change = "Change",
    contactDetails = "Contact",
    noContactDetails = "No phone or email on file",
    customerStatusActive = "Status: active",
    customerStatusPrefix = "Status: %s",
    recentWork = "Recent work",
    newestFirst = "Newest first",
    noCachedTickets = "No cached service orders yet. The first one you create appears here.",
    newOrder = "＋ New order",
    intakeEmptyTitle = "Search to begin",
    intakeEmptyDescription = "The full customer list is not shown by default. Search by name, phone or account.",
    intakeNoMatchTitle = "No customer found",
    intakeNoMatchDescription = "No cached customer matches “%s”. Check the details or create a customer.",
    matchingCustomers = "Matching customers",
    matchingCustomersCount = "%d match on this terminal. Tap one to start a ticket.",
    noPhoneOnFile = "No phone on file",
    select = "Select",
    serviceOrder = "Service order",
    itemsCountSuffix = "%d items",
    expectedPickup = "Pickup: %s",
    continueProcessing = "Continue ›",
    ticketsTitle = "Tickets",
    ticketsEmpty = "No synced tickets on this terminal yet.",
    serviceTicket = "Service ticket",
    syncLocalData = "Sync this terminal",
    backToMore = "Back to More",
    refreshing = "Refreshing…",
    refreshStatus = "Refresh status",
    shiftTitle = "Shift and cash",
    shiftIntro = "Shift, register and cash count are recorded separately. Clock in, then open the register to take cash safely.",
    shiftOfflineNotice = "Offline: you can keep selling cached products, but shift, register and cash movements need a connection.",
    shiftLoading = "Loading shift and register status",
    shiftLoadFailed = "If this does not load, check the connection and tap “Refresh status”.",
    reload = "Reload",
    staffShift = "Staff shift",
    shiftOpen = "Clocked in. You can start a break or keep selling.",
    shiftOnBreak = "On break. End the break before selling again.",
    shiftClosed = "Not clocked in. Clock in so cash sales attach to this handover.",
    clockingIn = "Clocking in…",
    clockIn = "Clock in",
    breakStarting = "Starting…",
    breakStart = "Start break",
    clockOut = "Clock out",
    breakEnding = "Ending break…",
    breakEnd = "End break",
    registerTitle = "Register",
    cashModeNone = "Cash is not enabled on this terminal. You can view the register but not take cash.",
    cashModeUntracked = "This terminal takes cash, but the store does not track the drawer amount.",
    cashModePersonal = "This terminal uses personal cash floats; each member of staff opens their own cash session.",
    cashModeShared = "This terminal uses a shared drawer. Once open you can record the float, pay-ins and pay-outs.",
    openingFloatRequired = "Opening float *",
    openingFloatOptional = "Opening float (optional)",
    openingFloatNeeded = "This store requires an opening float before the register can be opened.",
    registerOpening = "Opening…",
    openMyCashSession = "Open my cash session",
    openRegister = "Open the register",
    registerStatus = "Register status",
    thisTerminal = "This terminal",
    opened = "Open",
    notOpened = "Closed",
    cashSession = "Cash session",
    myPersonalCash = "My personal float",
    sharedDrawer = "Shared drawer",
    expectedCash = "Expected cash",
    thisRegister = "This register",
    netSales = "Net sales",
    outstandingOrders = "Unpaid orders",
    awaitingProcessing = "Awaiting processing",
    cashInOut = "Pay in / pay out",
    amountLabel = "Amount",
    reasonLabel = "Reason (at least 3 characters)",
    recording = "Recording…",
    payIn = "Pay in",
    payOut = "Pay out",
    countAndCloseMyCash = "Count and close my cash",
    closeRegisterZReport = "Close the register and print a Z report",
    closeRegisterHint = "Closing creates or updates this handover record. Confirm the counted amount.",
    countedCashRequired = "Counted cash *",
    countedCashOptional = "Counted cash (optional)",
    handoverNotes = "Handover notes (optional)",
    countedCashNeeded = "This store requires a counted amount before closing.",
    closing = "Closing…",
    confirmClose = "Confirm closing",
    notYet = "Not yet",
    closeNeedsManager = "Each member of staff opens and closes their own cash session; only an owner or manager closes the register itself.",
    recentZReports = "Recent Z reports",
    varianceLabel = "Variance",
    localData = "This terminal's data",
    cachedSummary = "%d products cached; %d cash orders waiting to sync.",
    confirmClockOutTitle = "Clock out?",
    confirmClockOutBody = "You will need to enter your PIN and clock in again before selling.",
    checkAgain = "Let me check",
    confirmClockOut = "Clock out",
    readyOnlineCash = "Ready for online cash",
    readyOfflineCash = "Ready for offline cash",
    cashDisabledStore = "Cash is not enabled for this store. An administrator must enable cash in the store's POS settings, then sync again.",
    cashNeedsShiftOnline = "A cash order needs an open shift and an open drawer.",
    cashNeedsShiftOffline = "An offline cash order must attach to an open shift and an open drawer, so cash taken without a network still has an owner.",
    startMyShift = "Start my shift",
    shiftStarted = "Shift started.",
    drawerOpeningCash = "Opening cash",
    openDrawerAndSync = "Open the drawer and sync",
    newCustomerTitle = "New customer",
    newCustomerHint = "Create the customer account first; you can raise a ticket straight after.",
    back = "Back",
    customerInfo = "Customer details",
    customerName = "Customer name",
    customerNamePlaceholder = "For example: Awa Diop",
    phoneNumber = "Phone number",
    phonePlaceholder = "For example: 77 000 0000",
    saving = "Saving…",
    saveCustomer = "Save customer",
    newTicketTitle = "New service ticket",
    newTicketHint = "Items and prices are entered in the next step.",
    ticketCustomer = "Customer",
    ticketType = "Ticket type",
    typeLaundry = "Laundry",
    typeCarWash = "Car wash",
    priorityTitle = "Priority",
    expectedPickupField = "Expected pickup (optional)",
    remarkOptional = "Note (optional)",
    remarkPlaceholder = "General service note",
    ticketNeedsNetwork = "Creating a ticket needs a connection. Try again once the network is back.",
    creating = "Creating…",
    createTicket = "Create the ticket",
    backToTickets = "Back to tickets",
    serviceItemsCount = "%d service items",
    ticketOfflineNotice = "Offline: cached items and the payment queue are visible; processing and pickup need a connection.",
    ticketFlow = "Ticket progress",
    cancelReasonRequired = "Cancellation reason (required to cancel)",
    confirmPickedUp = "Confirm the customer collected it (payment is checked)",
    updateToStatus = "Move to “%s”",
    serviceItems = "Service items",
    noServiceItems = "No service items on this ticket yet.",
    alreadyBilled = "Already on an order; it cannot be charged twice",
    pendingSyncNoBill = "Payment is waiting to sync on this terminal; it cannot be charged twice",
    appendServiceItem = "Add a service item",
    noCachedServices = "No cached service items. Sync first.",
    noServicesForType = "No service items for this ticket type. Configure the service catalogue in the back office first.",
    pendingService = "Service to add",
    itemTypePrefix = "Item type: %s",
    changeItemType = "Change item type",
    weightKg = "Weight (kg)",
    bagCount = "Bags",
    quantityPieces = "Quantity (pieces)",
    categoryOptional = "Category (optional)",
    colorOptional = "Colour (optional)",
    brandOptional = "Brand (optional)",
    materialOptional = "Material (optional)",
    defectsOptional = "Defects (optional)",
    specialRequestOptional = "Special request (optional)",
    itemNoteOptional = "Item note (optional)",
    adding = "Adding…",
    confirmAddItem = "Add the item",
    pickTypeThenService = "Choose the item type first, then a price for that service.",
    pickedTypeNowService = "“%s” selected. Now choose the service.",
    addToCartTitle = "Add to the till cart",
    addToCartHint = "Choose the items to charge now. Items already on an order, waiting to sync, or in the cart are left out.",
    linkedToOrder = "On an order",
    awaitingSync = "Waiting to sync",
    inCart = "In the cart",
    selected = "Selected",
    notSelected = "Not selected",
    somePaymentsQueued = "Cash for some items is still queued on this terminal; the rest can be charged separately.",
    addingTotalHint = "Adding %s. It can be paid in cash together with retail products or this customer's other tickets.",
    addingToCart = "Adding…",
    nothingToCharge = "Nothing to charge on this ticket.",
    bagsSuffix = "%s bags",
    piecesSuffix = "%s pieces",
    defectsPrefix = "Defects: %s",
    specialRequestPrefix = "Special request: %s",
    notePrefix = "Note: %s",
    editItem = "Edit item",
    deleteItem = "Delete item",
    deleteReasonRequired = "Reason for deleting (required)",
    confirmDeleteItem = "Delete the item",
    editServiceItem = "Edit the service item",
    editServiceItemHint = "Choose the item type, then a service available for it. Unit price and the right to change it are still checked by the server.",
    saveItem = "Save the item",
    cancelEdit = "Cancel",
    scanLabel = "Scan a label",
    productsServices = "Products and services",
    statisticsShort = "Figures",
    settingsShort = "Settings",
    customersCachedHint = "Customer records are kept on this terminal; a new customer syncs immediately when online.",
    nameAccountOrPhone = "Name, account or phone",
    newServiceTicket = "New service ticket",
    customerRegistration = "Create a customer",
    createCustomer = "Create the customer",
    noCachedMatches = "No cached customer matches.",
    noContactOnFile = "No contact details on file",
    tapToStartIntake = "Tap to start a ticket for them",
    productsHeading = "Products",
    syncedSellOffline = "Synced; can be sold offline",
    usingLocalCatalog = "Using the local catalogue",
    addToTillList = "Add to the till",
    servicePrices = "Service prices",
    scanIntro = "Works with the built-in scanner, a keyboard-wedge scanner, or typing a ticket number, order number, phone or customer name. Online it uses the same global search as the POS web app.",
    scanOrType = "Scan or type a keyword",
    searching = "Searching…",
    searchOnline = "Search online",
    startBuiltInScanner = "Start the built-in scanner",
    scanEmptyHint = "Type to search this terminal's cache, or search online for all orders, tickets and customers.",
    ticketPrefix = "Ticket %s",
    productAddToTill = "Product %s · add to the till",
    customerPrefix = "Customer %s",
    onlineSearchResults = "Online results",
    noMatchFound = "No cached record found. Tap to search online.",
    archiveNotification = "Archive",
    loading = "Loading…",
    refreshOrders = "Refresh orders",
    noOrdersToShow = "No orders to show. Connect and refresh.",
    orderPrefix = "Order %s",
    walkInCustomer = "Walk-in",
    tapToProcessOrder = "Tap to process",
    openOrderWhenOnline = "Open an order online to see its detail.",
    customerLabel = "Customer",
    orderStatus = "Order status",
    orderAmount = "Order amount",
    paidPrefix = "Paid %s",
    cashCollection = "Take cash",
    outstandingHint = "%s outstanding. An online payment uses the current shift and drawer.",
    tenderedForChange = "Cash received (for change)",
    chargeOutstanding = "Charge the outstanding amount",
    defaultChargeOutstanding = "Cash is recorded as the outstanding amount by default.",
    enterTenderAndChange = "Enter the amount received and give change",
    confirmTakeCash = "Take the cash",
    orderProcessing = "Order handling",
    confirmReceived = "Accept the order",
    confirmDelivered = "Mark delivered",
    orderItems = "Order items",
    quantityPrefix = "Quantity %s",
    paymentRecords = "Payments",
    periodToday = "Today",
    periodWeek = "This week",
    periodMonth = "This month",
    periodAll = "All",
    refreshData = "Refresh",
    ordersLabel = "Orders",
    ordersSummary = "%d orders · %d unpaid",
    ticketsLabel = "Tickets",
    ticketsSummary = "%d tickets · %d overdue",
    customersSummary = "%d customers · %d new today",
    statisticsWhenOnline = "Connect and refresh to load the figures.",
    refreshNotifications = "Refresh",
    noNotifications = "No notifications. Connect and refresh.",
    archive = "Archive",
    refreshTerminalSettings = "Refresh terminal settings",
    terminalLabel = "Terminal",
    printerDrawerScanner = "Printing, drawer and scanner",
    hardwareSettingsHint = "Check the built-in devices, then test and register the receipt printer and scanner.",
    openHardwareSettings = "Open hardware settings",
    cashHandlingMode = "Cash handling",
    terminalPreferences = "This terminal's preferences",
    terminalName = "Terminal name",
    autoLockSeconds = "Auto-lock after (seconds)",
    autoPrintCopies = "Copies to print",
    copiesSuffix = "%s copies",
    receiptPrinting = "Receipt printing",
    autoPrintOption = "Print automatically",
    manualPrintOption = "Print manually",
    cashRounding = "Cash rounding",
    roundingNone = "No rounding",
    roundingJiao = "To the nearest jiao",
    roundingYuan = "To the nearest yuan",
    saveTerminalSettings = "Save terminal settings",
    syncStatus = "Sync status",
    settingsWhenOnline = "Connect and refresh to load the terminal settings.",
    hardwareIntro = "This reads the Android POS native hardware service directly; device registration follows the same terminal-level configuration as the POS web app.",
    detecting = "Detecting…",
    refreshHardware = "Refresh hardware status",
    readingHardware = "Reading this terminal's hardware status.",
    hardwareModel = "Hardware model",
    builtInPrinter = "Built-in receipt printer",
    noBuiltInPrinter = "No supported built-in printer detected on this device",
    statusLabel = "Status",
    connected = "Connected",
    notConnected = "Not connected",
    printTestPage = "Print a test page",
    testAndRegister = "Test and register",
    builtInScanner = "Built-in scanner",
    noBuiltInScanner = "No supported built-in scanner detected on this device",
    connectedReadyToScan = "Connected and ready to scan",
    startScanTest = "Start a scan test",
    drawerTitle = "Cash drawer",
    drawerConnectedHint = "The drawer service is connected. A manual test first asks the server for an audited authorisation.",
    drawerUnavailable = "No cash drawer service is available on this device.",
    authoriseAndTestDrawer = "Request authorisation and test the drawer",
    hardwareManagerOnly = "Only an owner or manager can register devices, change the default printer or test the drawer by hand.",
    registeredDevices = "Registered devices",
    noRegisteredDevicesOnline = "No registered devices read for this terminal yet.",
    noRegisteredDevicesOffline = "Registered devices can be read once the network returns.",
    defaultReceiptPrinter = "Default receipt printer",
    deviceEnabled = "Enabled",
    deviceDisabled = "Disabled",
    bluetoothPrinter = "External Bluetooth printer",
    bluetoothIntro = "Pair the printer in Android's Bluetooth settings first, then test it here and bind it to a registered printer.",
    authoriseBluetooth = "Allow Bluetooth",
    readPairedDevices = "Read paired devices",
    noPairedPrinters = "No paired Bluetooth printer found yet.",
    paired = "Paired",
    testAndBindTo = "Test and bind to %s",
    needRegisteredPrinter = "Create and enable an external printer for this terminal in the back office first.",
    localReceiptQueue = "Local receipt queue",
    receiptQueueSummary = "%d waiting to print, %d failed. Failed jobs are not retried automatically, to avoid printing twice.",
    printNextReceipt = "Print the next receipt",
    useDefaultPrinterHint = "Print with the registered default receipt printer; the queue stays on this terminal.",
    openTicket = "Open the ticket",

)

private val COPY_FR = NativePosCopy(
    online = "En ligne",
    offline = "Hors ligne",
    offlineMode = "Mode hors ligne",
    syncing = "Synchronisation",
    synchronize = "Synchroniser",
    pendingSalesSuffix = "%d en attente de synchronisation",
    catalogTitle = "Catalogue",
    cartEmpty = "Le panier est vide.",
    amountDue = "Montant dû",
    checkout = "Encaisser",
    cashTendered = "Espèces reçues",
    changeDue = "Monnaie à rendre",
    subtotal = "Sous-total",
    tax = "Taxe",
    rounding = "Arrondi",
    total = "Total",
    receiptPrint = "Imprimer le reçu",
    receiptNone = "Sans reçu",
    receiptQueued = "Le reçu est dans la file d'impression de cette caisse.",
    saleSubmittedOnline = "Commande espèces envoyée. Si la connexion tombe avant la réponse, elle est renvoyée sous le même numéro de commande.",
    saleQueuedOffline = "Commande espèces enregistrée sur cette caisse. Elle sera synchronisée sous le même numéro dès le retour du réseau.",
    cashPaymentRecorded = "Paiement en espèces enregistré.",
    tenderBelowTotal = "Les espèces reçues ne peuvent pas être inférieures au montant dû.",
    cartIsEmpty = "Le panier est vide.",
    priceChanged = "Le prix, la remise ou la taxe a changé. Confirmez de nouveau le paiement.",
    shiftAndDrawerRequired = "Encaisser des espèces exige un service ouvert et un tiroir ouvert.",
    requiresNetwork = "Cette action demande une connexion. Réessayez dès le retour du réseau.",
    networkError = "Erreur réseau. Vérifiez la connexion de cette caisse et réessayez.",
    genericFailure = "L'opération n'a pas abouti. Vérifiez le réseau ou réessayez sous peu.",
    staleCatalogWarning = "Les produits et les prix de cette caisse datent de %d heures. Synchronisez avant de continuer à vendre.",
    printerNotConnected = "L'imprimante n'est pas connectée.",
    printerOutOfPaper = "L'imprimante n'a plus de papier. Chargez du papier thermique et réessayez.",
    printerCoverOpen = "Le capot de l'imprimante est ouvert.",
    printerOverheated = "L'imprimante est trop chaude. Réessayez sous peu.",
    drawerOpened = "Tiroir-caisse ouvert.",
    drawerDisconnected = "Le service du tiroir-caisse s'est déconnecté. Actualisez l'état du matériel et réessayez.",
    tabWorkspace = "Accueil",
    tabSale = "Caisse",
    tabIntake = "Nouveau bon",
    tabTickets = "Bons",
    tabMore = "Plus",
    menuMore = "Plus",
    menuCustomers = "Clients",
    menuCatalog = "Produits et services",
    menuScan = "Scanner pour rechercher",
    menuOrders = "Commandes",
    menuOrderDetail = "Détail de la commande",
    menuStatistics = "Chiffres d'activité",
    menuNotifications = "Notifications",
    menuShift = "Service et caisse",
    menuSettings = "Réglages de la caisse",
    menuHardware = "Impression et matériel",
    ticketDraft = "Brouillon",
    ticketPending = "En attente",
    ticketInProgress = "En cours",
    ticketReadyToPick = "Prêt à retirer",
    ticketPickedUp = "Retiré",
    ticketCancelled = "Annulé",
    ticketUnknown = "Inconnu",
    itemPendingWash = "En attente",
    itemWashing = "En cours",
    itemDone = "Terminé",
    itemReadyToPick = "Prêt à retirer",
    typeCloth = "Vêtement",
    typeCar = "Véhicule",
    typeShoe = "Chaussures",
    typeCarpet = "Tapis",
    priorityCritical = "Critique",
    priorityUrgent = "Express",
    priorityNormal = "Normal",
    devicePrinter = "Imprimante",
    deviceScanner = "Scanner",
    deviceCashDrawer = "Tiroir-caisse",
    moreNeedsNetwork = "%s demande une connexion. Les clients, le catalogue et les bons en cache restent disponibles sur cette caisse.",
    workspaceTitle = "Accueil",
    workspaceOnlineHint = "Cette caisse est en ligne ; l'état est vérifié en direct.",
    workspaceOfflineHint = "Cette caisse est hors ligne et utilise ses données en cache.",
    metricCatalog = "Catalogue",
    metricPendingOrders = "En attente de synchro",
    metricFailedOrders = "Rejetées",
    cashSectionTitle = "Caisse espèces",
    cashReadyOffline = "Le service et le tiroir sont prêts ; les espèces peuvent être encaissées hors ligne.",
    cashCheckedOnline = "Le service et le tiroir sont vérifiés en direct à l'ouverture de la caisse.",
    cashNeedsSync = "Rétablissez le réseau et synchronisez le service et le tiroir pour encaisser hors ligne.",
    openTill = "Ouvrir la caisse",
    synchronizing = "Synchronisation…",
    intakeTitle = "Accueil client",
    intakeOnlineHint = "Recherchez un client, puis créez un bon de service.",
    intakeOfflineHint = "Hors ligne vous pouvez chercher les clients en cache ; créer un client ou un bon demande une connexion.",
    newCustomer = "＋ Nouveau client",
    newCustomerShort = "Nouveau client",
    lookupTitle = "Rechercher un client",
    lookupHint = "Saisissez un nom, un numéro de téléphone ou un compte.",
    lookupLabel = "Nom, téléphone ou compte",
    lookupPlaceholder = "Par exemple : Awa Diop / 77 000 0000",
    search = "Rechercher",
    customerRecord = "Fiche client",
    change = "Changer",
    contactDetails = "Contact",
    noContactDetails = "Aucun téléphone ni e-mail enregistré",
    customerStatusActive = "Statut : actif",
    customerStatusPrefix = "Statut : %s",
    recentWork = "Travaux récents",
    newestFirst = "Les plus récents d'abord",
    noCachedTickets = "Aucune commande de service en cache. La première que vous créez apparaîtra ici.",
    newOrder = "＋ Nouvelle commande",
    intakeEmptyTitle = "Lancez une recherche",
    intakeEmptyDescription = "La liste complète des clients n'est pas affichée par défaut. Cherchez par nom, téléphone ou compte.",
    intakeNoMatchTitle = "Aucun client trouvé",
    intakeNoMatchDescription = "Aucun client en cache ne correspond à « %s ». Vérifiez les informations ou créez un client.",
    matchingCustomers = "Clients correspondants",
    matchingCustomersCount = "%d résultat sur cette caisse. Touchez-en un pour créer un bon.",
    noPhoneOnFile = "Aucun téléphone enregistré",
    select = "Choisir",
    serviceOrder = "Commande de service",
    itemsCountSuffix = "%d articles",
    expectedPickup = "Retrait : %s",
    continueProcessing = "Continuer ›",
    ticketsTitle = "Bons",
    ticketsEmpty = "Aucun bon synchronisé sur cette caisse.",
    serviceTicket = "Bon de service",
    syncLocalData = "Synchroniser cette caisse",
    backToMore = "Retour à Plus",
    refreshing = "Actualisation…",
    refreshStatus = "Actualiser l'état",
    shiftTitle = "Service et caisse",
    shiftIntro = "Le service, la caisse et le comptage sont enregistrés séparément. Pointez, puis ouvrez la caisse pour encaisser en sécurité.",
    shiftOfflineNotice = "Hors ligne : vous pouvez continuer à vendre les produits en cache, mais le service, la caisse et les mouvements d'espèces demandent une connexion.",
    shiftLoading = "Chargement de l'état du service et de la caisse",
    shiftLoadFailed = "Si le chargement échoue, vérifiez la connexion puis touchez « Actualiser l'état ».",
    reload = "Recharger",
    staffShift = "Service du personnel",
    shiftOpen = "Pointé. Vous pouvez prendre une pause ou continuer à vendre.",
    shiftOnBreak = "En pause. Terminez la pause avant de vendre à nouveau.",
    shiftClosed = "Non pointé. Pointez pour que les ventes en espèces soient rattachées à ce service.",
    clockingIn = "Pointage en cours…",
    clockIn = "Pointer l'arrivée",
    breakStarting = "Démarrage…",
    breakStart = "Commencer la pause",
    clockOut = "Pointer la sortie",
    breakEnding = "Fin de pause…",
    breakEnd = "Terminer la pause",
    registerTitle = "Caisse",
    cashModeNone = "Les espèces ne sont pas activées sur cette caisse. Vous pouvez consulter l'état mais pas encaisser.",
    cashModeUntracked = "Cette caisse accepte les espèces, mais le magasin ne suit pas le montant du tiroir.",
    cashModePersonal = "Cette caisse utilise le fonds personnel ; chaque employé ouvre sa propre session.",
    cashModeShared = "Cette caisse utilise un tiroir partagé. Une fois ouvert, vous pouvez enregistrer le fonds, les entrées et les sorties.",
    openingFloatRequired = "Fonds d'ouverture *",
    openingFloatOptional = "Fonds d'ouverture (facultatif)",
    openingFloatNeeded = "Ce magasin exige un fonds d'ouverture avant d'ouvrir la caisse.",
    registerOpening = "Ouverture…",
    openMyCashSession = "Ouvrir ma session",
    openRegister = "Ouvrir la caisse",
    registerStatus = "État de la caisse",
    thisTerminal = "Cette caisse",
    opened = "Ouverte",
    notOpened = "Fermée",
    cashSession = "Session de caisse",
    myPersonalCash = "Mon fonds personnel",
    sharedDrawer = "Tiroir partagé",
    expectedCash = "Espèces attendues",
    thisRegister = "Cette caisse",
    netSales = "Ventes nettes",
    outstandingOrders = "Commandes impayées",
    awaitingProcessing = "En attente de traitement",
    cashInOut = "Entrée / sortie d'espèces",
    amountLabel = "Montant",
    reasonLabel = "Motif (3 caractères minimum)",
    recording = "Enregistrement…",
    payIn = "Entrée d'espèces",
    payOut = "Sortie d'espèces",
    countAndCloseMyCash = "Compter et clôturer mon fonds",
    closeRegisterZReport = "Clôturer la caisse et imprimer un rapport Z",
    closeRegisterHint = "La clôture crée ou met à jour cet enregistrement de passation. Confirmez le montant compté.",
    countedCashRequired = "Espèces comptées *",
    countedCashOptional = "Espèces comptées (facultatif)",
    handoverNotes = "Notes de passation (facultatif)",
    countedCashNeeded = "Ce magasin exige un montant compté avant la clôture.",
    closing = "Clôture…",
    confirmClose = "Confirmer la clôture",
    notYet = "Pas maintenant",
    closeNeedsManager = "Chaque employé ouvre et clôture sa propre session ; seul un propriétaire ou un responsable clôture la caisse.",
    recentZReports = "Rapports Z récents",
    varianceLabel = "Écart",
    localData = "Données de cette caisse",
    cachedSummary = "%d produits en cache ; %d commandes espèces en attente de synchro.",
    confirmClockOutTitle = "Pointer la sortie ?",
    confirmClockOutBody = "Vous devrez saisir votre PIN et pointer de nouveau avant de vendre.",
    checkAgain = "Je vérifie",
    confirmClockOut = "Pointer la sortie",
    readyOnlineCash = "Prêt pour les espèces en ligne",
    readyOfflineCash = "Prêt pour les espèces hors ligne",
    cashDisabledStore = "Les espèces ne sont pas activées pour ce magasin. Un administrateur doit les activer dans les réglages POS, puis resynchroniser.",
    cashNeedsShiftOnline = "Une commande espèces exige un service ouvert et un tiroir ouvert.",
    cashNeedsShiftOffline = "Une commande espèces hors ligne doit être rattachée à un service et un tiroir ouverts, afin que les espèces encaissées sans réseau restent attribuées.",
    startMyShift = "Commencer mon service",
    shiftStarted = "Service commencé.",
    drawerOpeningCash = "Espèces d'ouverture",
    openDrawerAndSync = "Ouvrir le tiroir et synchroniser",
    newCustomerTitle = "Nouveau client",
    newCustomerHint = "Créez d'abord le compte client ; vous pourrez ensuite créer un bon.",
    back = "Retour",
    customerInfo = "Informations client",
    customerName = "Nom du client",
    customerNamePlaceholder = "Par exemple : Awa Diop",
    phoneNumber = "Numéro de téléphone",
    phonePlaceholder = "Par exemple : 77 000 0000",
    saving = "Enregistrement…",
    saveCustomer = "Enregistrer le client",
    newTicketTitle = "Nouveau bon de service",
    newTicketHint = "Les articles et les prix sont saisis à l'étape suivante.",
    ticketCustomer = "Client",
    ticketType = "Type de bon",
    typeLaundry = "Blanchisserie",
    typeCarWash = "Lavage auto",
    priorityTitle = "Priorité",
    expectedPickupField = "Retrait prévu (facultatif)",
    remarkOptional = "Note (facultatif)",
    remarkPlaceholder = "Note de service générale",
    ticketNeedsNetwork = "Créer un bon demande une connexion. Réessayez dès le retour du réseau.",
    creating = "Création…",
    createTicket = "Créer le bon",
    backToTickets = "Retour aux bons",
    serviceItemsCount = "%d articles de service",
    ticketOfflineNotice = "Hors ligne : les articles en cache et la file de paiement sont visibles ; le traitement et le retrait demandent une connexion.",
    ticketFlow = "Progression du bon",
    cancelReasonRequired = "Motif d'annulation (obligatoire pour annuler)",
    confirmPickedUp = "Confirmer le retrait par le client (le paiement est vérifié)",
    updateToStatus = "Passer à « %s »",
    serviceItems = "Articles de service",
    noServiceItems = "Aucun article de service sur ce bon.",
    alreadyBilled = "Déjà sur une commande ; ne peut pas être facturé deux fois",
    pendingSyncNoBill = "Le paiement attend la synchro sur cette caisse ; il ne peut pas être facturé deux fois",
    appendServiceItem = "Ajouter un article de service",
    noCachedServices = "Aucun article de service en cache. Synchronisez d'abord.",
    noServicesForType = "Aucun article pour ce type de bon. Configurez le catalogue de services dans l'administration.",
    pendingService = "Service à ajouter",
    itemTypePrefix = "Type d'article : %s",
    changeItemType = "Changer de type",
    weightKg = "Poids (kg)",
    bagCount = "Sacs",
    quantityPieces = "Quantité (pièces)",
    categoryOptional = "Catégorie (facultatif)",
    colorOptional = "Couleur (facultatif)",
    brandOptional = "Marque (facultatif)",
    materialOptional = "Matière (facultatif)",
    defectsOptional = "Défauts (facultatif)",
    specialRequestOptional = "Demande particulière (facultatif)",
    itemNoteOptional = "Note d'article (facultatif)",
    adding = "Ajout…",
    confirmAddItem = "Ajouter l'article",
    pickTypeThenService = "Choisissez d'abord le type d'article, puis un tarif pour ce service.",
    pickedTypeNowService = "« %s » sélectionné. Choisissez maintenant le service.",
    addToCartTitle = "Ajouter au panier de caisse",
    addToCartHint = "Choisissez les articles à facturer. Ceux déjà sur une commande, en attente de synchro ou dans le panier sont exclus.",
    linkedToOrder = "Sur une commande",
    awaitingSync = "En attente de synchro",
    inCart = "Dans le panier",
    selected = "Sélectionné",
    notSelected = "Non sélectionné",
    somePaymentsQueued = "Les espèces de certains articles sont encore en file sur cette caisse ; les autres peuvent être facturés séparément.",
    addingTotalHint = "Ajout de %s. Peut être réglé en espèces avec des produits ou les autres bons de ce client.",
    addingToCart = "Ajout…",
    nothingToCharge = "Rien à facturer sur ce bon.",
    bagsSuffix = "%s sacs",
    piecesSuffix = "%s pièces",
    defectsPrefix = "Défauts : %s",
    specialRequestPrefix = "Demande particulière : %s",
    notePrefix = "Note : %s",
    editItem = "Modifier l'article",
    deleteItem = "Supprimer l'article",
    deleteReasonRequired = "Motif de suppression (obligatoire)",
    confirmDeleteItem = "Supprimer l'article",
    editServiceItem = "Modifier l'article de service",
    editServiceItemHint = "Choisissez le type d'article, puis un service disponible. Le prix unitaire et le droit de le modifier restent vérifiés par le serveur.",
    saveItem = "Enregistrer l'article",
    cancelEdit = "Annuler",
    scanLabel = "Scanner une étiquette",
    productsServices = "Produits et services",
    statisticsShort = "Chiffres",
    settingsShort = "Réglages",
    customersCachedHint = "Les fiches clients sont conservées sur cette caisse ; un nouveau client est synchronisé immédiatement en ligne.",
    nameAccountOrPhone = "Nom, compte ou téléphone",
    newServiceTicket = "Nouveau bon de service",
    customerRegistration = "Créer un client",
    createCustomer = "Créer le client",
    noCachedMatches = "Aucun client en cache ne correspond.",
    noContactOnFile = "Aucune coordonnée enregistrée",
    tapToStartIntake = "Touchez pour créer un bon pour ce client",
    productsHeading = "Produits",
    syncedSellOffline = "Synchronisé ; vendable hors ligne",
    usingLocalCatalog = "Catalogue local utilisé",
    addToTillList = "Ajouter à la caisse",
    servicePrices = "Tarifs des services",
    scanIntro = "Fonctionne avec le scanner intégré, une douchette clavier, ou en saisissant un numéro de bon, de commande, un téléphone ou un nom. En ligne, la même recherche globale que le POS web est utilisée.",
    scanOrType = "Scannez ou saisissez un mot-clé",
    searching = "Recherche…",
    searchOnline = "Rechercher en ligne",
    startBuiltInScanner = "Démarrer le scanner intégré",
    scanEmptyHint = "Saisissez pour chercher dans le cache de cette caisse, ou en ligne pour toutes les commandes, bons et clients.",
    ticketPrefix = "Bon %s",
    productAddToTill = "Produit %s · ajouter à la caisse",
    customerPrefix = "Client %s",
    onlineSearchResults = "Résultats en ligne",
    noMatchFound = "Aucun enregistrement en cache. Touchez pour chercher en ligne.",
    archiveNotification = "Archiver",
    loading = "Chargement…",
    refreshOrders = "Actualiser les commandes",
    noOrdersToShow = "Aucune commande à afficher. Connectez-vous et actualisez.",
    orderPrefix = "Commande %s",
    walkInCustomer = "Client de passage",
    tapToProcessOrder = "Touchez pour traiter",
    openOrderWhenOnline = "Ouvrez une commande en ligne pour voir le détail.",
    customerLabel = "Client",
    orderStatus = "État de la commande",
    orderAmount = "Montant de la commande",
    paidPrefix = "Payé %s",
    cashCollection = "Encaisser",
    outstandingHint = "%s restant dû. Un paiement en ligne utilise le service et le tiroir en cours.",
    tenderedForChange = "Espèces reçues (pour la monnaie)",
    chargeOutstanding = "Facturer le montant restant",
    defaultChargeOutstanding = "Les espèces sont enregistrées par défaut au montant restant dû.",
    enterTenderAndChange = "Saisir le montant reçu et rendre la monnaie",
    confirmTakeCash = "Encaisser",
    orderProcessing = "Traitement de la commande",
    confirmReceived = "Accepter la commande",
    confirmDelivered = "Marquer livrée",
    orderItems = "Articles de la commande",
    quantityPrefix = "Quantité %s",
    paymentRecords = "Paiements",
    periodToday = "Aujourd'hui",
    periodWeek = "Cette semaine",
    periodMonth = "Ce mois",
    periodAll = "Tout",
    refreshData = "Actualiser",
    ordersLabel = "Commandes",
    ordersSummary = "%d commandes · %d impayées",
    ticketsLabel = "Bons",
    ticketsSummary = "%d bons · %d en retard",
    customersSummary = "%d clients · %d nouveaux aujourd'hui",
    statisticsWhenOnline = "Connectez-vous et actualisez pour charger les chiffres.",
    refreshNotifications = "Actualiser",
    noNotifications = "Aucune notification. Connectez-vous et actualisez.",
    archive = "Archiver",
    refreshTerminalSettings = "Actualiser les réglages",
    terminalLabel = "Caisse",
    printerDrawerScanner = "Impression, tiroir et scanner",
    hardwareSettingsHint = "Vérifiez les appareils intégrés, puis testez et enregistrez l'imprimante et le scanner.",
    openHardwareSettings = "Ouvrir les réglages matériel",
    cashHandlingMode = "Gestion des espèces",
    terminalPreferences = "Préférences de cette caisse",
    terminalName = "Nom de la caisse",
    autoLockSeconds = "Verrouillage auto (secondes)",
    autoPrintCopies = "Nombre de copies",
    copiesSuffix = "%s copies",
    receiptPrinting = "Impression des reçus",
    autoPrintOption = "Impression automatique",
    manualPrintOption = "Impression manuelle",
    cashRounding = "Arrondi des espèces",
    roundingNone = "Aucun arrondi",
    roundingJiao = "Au jiao le plus proche",
    roundingYuan = "Au yuan le plus proche",
    saveTerminalSettings = "Enregistrer les réglages",
    syncStatus = "État de synchro",
    settingsWhenOnline = "Connectez-vous et actualisez pour charger les réglages.",
    hardwareIntro = "Ceci lit directement le service matériel natif du POS Android ; l'enregistrement des appareils suit la configuration de la caisse du POS web.",
    detecting = "Détection…",
    refreshHardware = "Actualiser l'état du matériel",
    readingHardware = "Lecture de l'état du matériel.",
    hardwareModel = "Modèle du matériel",
    builtInPrinter = "Imprimante de reçus intégrée",
    noBuiltInPrinter = "Aucune imprimante intégrée prise en charge détectée",
    statusLabel = "État",
    connected = "Connectée",
    notConnected = "Non connectée",
    printTestPage = "Imprimer une page de test",
    testAndRegister = "Tester et enregistrer",
    builtInScanner = "Scanner intégré",
    noBuiltInScanner = "Aucun scanner intégré pris en charge détecté",
    connectedReadyToScan = "Connecté et prêt à scanner",
    startScanTest = "Lancer un test de scan",
    drawerTitle = "Tiroir-caisse",
    drawerConnectedHint = "Le service du tiroir est connecté. Un test manuel demande d'abord une autorisation auditée au serveur.",
    drawerUnavailable = "Aucun service de tiroir-caisse disponible sur cet appareil.",
    authoriseAndTestDrawer = "Demander l'autorisation et tester le tiroir",
    hardwareManagerOnly = "Seul un propriétaire ou un responsable peut enregistrer des appareils, changer l'imprimante par défaut ou tester le tiroir.",
    registeredDevices = "Appareils enregistrés",
    noRegisteredDevicesOnline = "Aucun appareil enregistré lu pour cette caisse.",
    noRegisteredDevicesOffline = "Les appareils enregistrés pourront être lus au retour du réseau.",
    defaultReceiptPrinter = "Imprimante de reçus par défaut",
    deviceEnabled = "Activé",
    deviceDisabled = "Désactivé",
    bluetoothPrinter = "Imprimante Bluetooth externe",
    bluetoothIntro = "Associez d'abord l'imprimante dans les réglages Bluetooth d'Android, puis testez-la ici et liez-la à une imprimante enregistrée.",
    authoriseBluetooth = "Autoriser le Bluetooth",
    readPairedDevices = "Lire les appareils associés",
    noPairedPrinters = "Aucune imprimante Bluetooth associée trouvée.",
    paired = "Associée",
    testAndBindTo = "Tester et lier à %s",
    needRegisteredPrinter = "Créez et activez d'abord une imprimante externe pour cette caisse dans l'administration.",
    localReceiptQueue = "File de reçus locale",
    receiptQueueSummary = "%d en attente, %d en échec. Les travaux en échec ne sont pas relancés automatiquement, pour éviter une double impression.",
    printNextReceipt = "Imprimer le reçu suivant",
    useDefaultPrinterHint = "Imprimez avec l'imprimante de reçus par défaut enregistrée ; la file reste sur cette caisse.",
    openTicket = "Ouvrir le bon",

)

/** Copy for the terminal's selected language, falling back to Chinese. */
internal fun nativePosCopy(languageCode: String?): NativePosCopy =
    when (languageCode?.trim()?.lowercase()) {
        "en" -> COPY_EN
        "fr" -> COPY_FR
        else -> COPY_ZH
    }
