-- Default Email/Push notification templates and configs for Demo Tenant 1 (CLEAN-001).
--
-- This is seed data, not schema migration. It is intentionally idempotent and
-- uses fixed ULIDs so local/dev environments can be reseeded safely.

-- tenant_id : 01KRERJN800000000000000001

INSERT INTO notification_templates (
  id, tenant_id, template_code, template_name, notice_type, locale,
  title_template, content_template, variables, is_system, is_enabled
)
VALUES
  ('01SEED0200TPLORDCRT0000001', NULL, 'email.order.created', 'Order created email', 'business', 'en',
   'Order {{orderNo}} received',
   'Hi {{customerName}}, we received order {{orderNo}}. Total: {{totalAmount}}.',
   '[{"name":"orderNo"},{"name":"customerName"},{"name":"totalAmount"}]'::jsonb, true, true),
  ('01SEED0200TPLORDCRT0000002', NULL, 'email.order.created', 'Email commande creee', 'business', 'fr',
   'Commande {{orderNo}} recue',
   'Bonjour {{customerName}}, nous avons recu la commande {{orderNo}}. Total: {{totalAmount}}.',
   '[{"name":"orderNo"},{"name":"customerName"},{"name":"totalAmount"}]'::jsonb, true, true),
  ('01SEED0200TPLORDCRT0000003', NULL, 'email.order.created', '订单创建邮件', 'business', 'zh-CN',
   '订单 {{orderNo}} 已受理',
   '{{customerName}}，您的订单 {{orderNo}} 已受理。金额：{{totalAmount}}。',
   '[{"name":"orderNo"},{"name":"customerName"},{"name":"totalAmount"}]'::jsonb, true, true),

  ('01SEED0200TPLORDCMP0000001', NULL, 'email.order.completed', 'Order completed email', 'business', 'en',
   'Order {{orderNo}} completed',
   'Hi {{customerName}}, order {{orderNo}} is complete and ready. Total: {{totalAmount}}.',
   '[{"name":"orderNo"},{"name":"customerName"},{"name":"totalAmount"}]'::jsonb, true, true),
  ('01SEED0200TPLORDCMP0000002', NULL, 'email.order.completed', 'Email commande terminee', 'business', 'fr',
   'Commande {{orderNo}} terminee',
   'Bonjour {{customerName}}, la commande {{orderNo}} est terminee. Total: {{totalAmount}}.',
   '[{"name":"orderNo"},{"name":"customerName"},{"name":"totalAmount"}]'::jsonb, true, true),
  ('01SEED0200TPLORDCMP0000003', NULL, 'email.order.completed', '订单完成邮件', 'business', 'zh-CN',
   '订单 {{orderNo}} 已完成',
   '{{customerName}}，您的订单 {{orderNo}} 已完成。金额：{{totalAmount}}。',
   '[{"name":"orderNo"},{"name":"customerName"},{"name":"totalAmount"}]'::jsonb, true, true),

  ('01SEED0200TPLTKTOVD0000001', NULL, 'email.ticket.overdue', 'Overdue pickup email', 'business', 'en',
   'Pickup reminder for {{ticketNo}}',
   'Hi {{customerName}}, ticket {{ticketNo}} is ready for pickup. Expected pickup time: {{expectedPickupAt}}.',
   '[{"name":"ticketNo"},{"name":"customerName"},{"name":"expectedPickupAt"}]'::jsonb, true, true),
  ('01SEED0200TPLTKTOVD0000002', NULL, 'email.ticket.overdue', 'Rappel retrait email', 'business', 'fr',
   'Rappel retrait {{ticketNo}}',
   'Bonjour {{customerName}}, le ticket {{ticketNo}} est pret a etre retire. Date prevue: {{expectedPickupAt}}.',
   '[{"name":"ticketNo"},{"name":"customerName"},{"name":"expectedPickupAt"}]'::jsonb, true, true),
  ('01SEED0200TPLTKTOVD0000003', NULL, 'email.ticket.overdue', '逾期取件邮件', 'business', 'zh-CN',
   '取件提醒 {{ticketNo}}',
   '{{customerName}}，工单 {{ticketNo}} 已可取件，预计取件时间：{{expectedPickupAt}}。',
   '[{"name":"ticketNo"},{"name":"customerName"},{"name":"expectedPickupAt"}]'::jsonb, true, true),

  ('01SEED0200TPLDLVSTS0000001', NULL, 'email.delivery.status_changed', 'Delivery status email', 'business', 'en',
   'Delivery update: {{toStatus}}',
   'Hi {{customerName}}, your {{type}} delivery task is now {{toStatus}}.',
   '[{"name":"customerName"},{"name":"type"},{"name":"toStatus"}]'::jsonb, true, true),
  ('01SEED0200TPLDLVSTS0000002', NULL, 'email.delivery.status_changed', 'Email statut livraison', 'business', 'fr',
   'Mise a jour livraison: {{toStatus}}',
   'Bonjour {{customerName}}, votre livraison {{type}} est maintenant {{toStatus}}.',
   '[{"name":"customerName"},{"name":"type"},{"name":"toStatus"}]'::jsonb, true, true),
  ('01SEED0200TPLDLVSTS0000003', NULL, 'email.delivery.status_changed', '配送状态邮件', 'business', 'zh-CN',
   '配送状态更新：{{toStatus}}',
   '{{customerName}}，您的 {{type}} 配送任务状态已更新为 {{toStatus}}。',
   '[{"name":"customerName"},{"name":"type"},{"name":"toStatus"}]'::jsonb, true, true),

  ('01SEED0200TPLAPPACC0000001', NULL, 'email.appointment.accepted', 'Appointment accepted email', 'business', 'en',
   'Appointment accepted',
   'Your {{appointmentType}} appointment for {{expectedAt}} has been accepted. Address: {{address}}.',
   '[{"name":"appointmentType"},{"name":"expectedAt"},{"name":"address"}]'::jsonb, true, true),
  ('01SEED0200TPLAPPACC0000002', NULL, 'email.appointment.accepted', 'Email rendez-vous accepte', 'business', 'fr',
   'Rendez-vous accepte',
   'Votre rendez-vous {{appointmentType}} du {{expectedAt}} est accepte. Adresse: {{address}}.',
   '[{"name":"appointmentType"},{"name":"expectedAt"},{"name":"address"}]'::jsonb, true, true),
  ('01SEED0200TPLAPPACC0000003', NULL, 'email.appointment.accepted', '预约确认邮件', 'business', 'zh-CN',
   '预约已确认',
   '您的 {{appointmentType}} 预约已确认，时间：{{expectedAt}}。地址：{{address}}。',
   '[{"name":"appointmentType"},{"name":"expectedAt"},{"name":"address"}]'::jsonb, true, true),

  ('01SEED0200TPLAPPREJ0000001', NULL, 'email.appointment.rejected', 'Appointment rejected email', 'business', 'en',
   'Appointment rejected',
   'Your {{appointmentType}} appointment for {{expectedAt}} was rejected. Reason: {{reason}}.',
   '[{"name":"appointmentType"},{"name":"expectedAt"},{"name":"reason"}]'::jsonb, true, true),
  ('01SEED0200TPLAPPREJ0000002', NULL, 'email.appointment.rejected', 'Email rendez-vous refuse', 'business', 'fr',
   'Rendez-vous refuse',
   'Votre rendez-vous {{appointmentType}} du {{expectedAt}} est refuse. Motif: {{reason}}.',
   '[{"name":"appointmentType"},{"name":"expectedAt"},{"name":"reason"}]'::jsonb, true, true),
  ('01SEED0200TPLAPPREJ0000003', NULL, 'email.appointment.rejected', '预约拒绝邮件', 'business', 'zh-CN',
   '预约未通过',
   '您的 {{appointmentType}} 预约未通过，时间：{{expectedAt}}。原因：{{reason}}。',
   '[{"name":"appointmentType"},{"name":"expectedAt"},{"name":"reason"}]'::jsonb, true, true),

  ('01SEED0200TPLRFDAPP0000001', NULL, 'email.refund.approved', 'Refund approved email', 'business', 'en',
   'Refund approved',
   'Your refund request for order {{orderId}} has been approved. Amount: {{amount}}. Status: {{status}}.',
   '[{"name":"orderId"},{"name":"amount"},{"name":"status"}]'::jsonb, true, true),
  ('01SEED0200TPLRFDAPP0000002', NULL, 'email.refund.approved', 'Email remboursement approuve', 'business', 'fr',
   'Remboursement approuve',
   'Votre demande de remboursement pour la commande {{orderId}} est approuvee. Montant: {{amount}}. Statut: {{status}}.',
   '[{"name":"orderId"},{"name":"amount"},{"name":"status"}]'::jsonb, true, true),
  ('01SEED0200TPLRFDAPP0000003', NULL, 'email.refund.approved', '退款批准邮件', 'business', 'zh-CN',
   '退款申请已批准',
   '您的订单 {{orderId}} 退款申请已批准。金额：{{amount}}。状态：{{status}}。',
   '[{"name":"orderId"},{"name":"amount"},{"name":"status"}]'::jsonb, true, true),

  ('01SEED0200TPLRFDREJ0000001', NULL, 'email.refund.rejected', 'Refund rejected email', 'business', 'en',
   'Refund rejected',
   'Your refund request for order {{orderId}} was rejected. Reason: {{rejectionReason}}.',
   '[{"name":"orderId"},{"name":"rejectionReason"}]'::jsonb, true, true),
  ('01SEED0200TPLRFDREJ0000002', NULL, 'email.refund.rejected', 'Email remboursement refuse', 'business', 'fr',
   'Remboursement refuse',
   'Votre demande de remboursement pour la commande {{orderId}} est refusee. Motif: {{rejectionReason}}.',
   '[{"name":"orderId"},{"name":"rejectionReason"}]'::jsonb, true, true),
  ('01SEED0200TPLRFDREJ0000003', NULL, 'email.refund.rejected', '退款拒绝邮件', 'business', 'zh-CN',
   '退款申请未通过',
   '您的订单 {{orderId}} 退款申请未通过。原因：{{rejectionReason}}。',
   '[{"name":"orderId"},{"name":"rejectionReason"}]'::jsonb, true, true),

  ('01SEED0200TPLDLVPSH0000001', NULL, 'push.delivery.status_changed', 'Delivery status push', 'business', 'en',
   'Delivery update',
   'Your {{type}} delivery is now {{toStatus}}.',
   '[{"name":"type"},{"name":"toStatus"}]'::jsonb, true, true),
  ('01SEED0200TPLDLVPSH0000002', NULL, 'push.delivery.status_changed', 'Push statut livraison', 'business', 'fr',
   'Mise a jour livraison',
   'Votre livraison {{type}} est maintenant {{toStatus}}.',
   '[{"name":"type"},{"name":"toStatus"}]'::jsonb, true, true),
  ('01SEED0200TPLDLVPSH0000003', NULL, 'push.delivery.status_changed', '配送状态推送', 'business', 'zh-CN',
   '配送状态更新',
   '您的 {{type}} 配送任务状态已更新为 {{toStatus}}。',
   '[{"name":"type"},{"name":"toStatus"}]'::jsonb, true, true),

  ('01SEED0200TPLRFDPSH0000001', NULL, 'push.refund.approved', 'Refund approved push', 'business', 'en',
   'Refund approved',
   'Your refund of {{amount}} has been approved.',
   '[{"name":"amount"}]'::jsonb, true, true),
  ('01SEED0200TPLRFDPSH0000002', NULL, 'push.refund.approved', 'Push remboursement approuve', 'business', 'fr',
   'Remboursement approuve',
   'Votre remboursement de {{amount}} est approuve.',
   '[{"name":"amount"}]'::jsonb, true, true),
  ('01SEED0200TPLRFDPSH0000003', NULL, 'push.refund.approved', '退款批准推送', 'business', 'zh-CN',
   '退款已批准',
   '您的退款 {{amount}} 已批准。',
   '[{"name":"amount"}]'::jsonb, true, true),

  -- Ready for pickup. Sent once when the ticket reaches ready_to_pick, unlike
  -- ticket.overdue which chases items nobody has collected.
  ('01SEED0200TPLTKTRDY0000001', NULL, 'email.ticket.ready_for_pickup', 'Ready for pickup email', 'business', 'en',
   'Your order {{ticketNo}} is ready',
   'Hi {{customerName}}, your order {{ticketNo}} is clean and ready to collect.',
   '[{"name":"ticketNo"},{"name":"customerName"},{"name":"expectedPickupAt"}]'::jsonb, true, true),
  ('01SEED0200TPLTKTRDY0000002', NULL, 'email.ticket.ready_for_pickup', 'Email pret a retirer', 'business', 'fr',
   'Votre commande {{ticketNo}} est prete',
   'Bonjour {{customerName}}, votre commande {{ticketNo}} est propre et prete a etre retiree.',
   '[{"name":"ticketNo"},{"name":"customerName"},{"name":"expectedPickupAt"}]'::jsonb, true, true),
  ('01SEED0200TPLTKTRDY0000003', NULL, 'email.ticket.ready_for_pickup', '可取件邮件', 'business', 'zh-CN',
   '您的订单 {{ticketNo}} 已可取件',
   '{{customerName}}，您的订单 {{ticketNo}} 已清洗完成，可以取件了。',
   '[{"name":"ticketNo"},{"name":"customerName"},{"name":"expectedPickupAt"}]'::jsonb, true, true),

  ('01SEED0200TPLTKTRPS0000001', NULL, 'push.ticket.ready_for_pickup', 'Ready for pickup push', 'business', 'en',
   'Ready for pickup',
   'Order {{ticketNo}} is clean and ready to collect.',
   '[{"name":"ticketNo"}]'::jsonb, true, true),
  ('01SEED0200TPLTKTRPS0000002', NULL, 'push.ticket.ready_for_pickup', 'Push pret a retirer', 'business', 'fr',
   'Pret a retirer',
   'La commande {{ticketNo}} est prete a etre retiree.',
   '[{"name":"ticketNo"}]'::jsonb, true, true),
  ('01SEED0200TPLTKTRPS0000003', NULL, 'push.ticket.ready_for_pickup', '可取件推送', 'business', 'zh-CN',
   '可以取件了',
   '订单 {{ticketNo}} 已清洗完成，可以取件了。',
   '[{"name":"ticketNo"}]'::jsonb, true, true)
ON CONFLICT (id) DO UPDATE SET
  template_name = EXCLUDED.template_name,
  locale = EXCLUDED.locale,
  title_template = EXCLUDED.title_template,
  content_template = EXCLUDED.content_template,
  variables = EXCLUDED.variables,
  is_system = EXCLUDED.is_system,
  is_enabled = EXCLUDED.is_enabled,
  updated_at = now();

INSERT INTO notification_configs (
  id, tenant_id, template_id, config_name, notice_type, trigger_type,
  trigger_event, channel, recipient_type, frequency_limit,
  frequency_window_minutes, is_enabled
)
VALUES
  ('01SEED0200CFGORDCRT0000001', '01KRERJN800000000000000001', '01SEED0200TPLORDCRT0000001',
   'Order created customer email', 'business', 'event', 'order.created', 'email', 'customer', 3, 60, true),
  ('01SEED0200CFGORDCMP0000001', '01KRERJN800000000000000001', '01SEED0200TPLORDCMP0000001',
   'Order completed customer email', 'business', 'event', 'order.completed', 'email', 'customer', 3, 60, true),
  ('01SEED0200CFGTKTOVD0000001', '01KRERJN800000000000000001', '01SEED0200TPLTKTOVD0000001',
   'Overdue pickup customer email', 'business', 'event', 'ticket.overdue', 'email', 'customer', 1, 1440, true),
  ('01SEED0200CFGDLVSTS0000001', '01KRERJN800000000000000001', '01SEED0200TPLDLVSTS0000001',
   'Delivery status customer email', 'business', 'event', 'delivery.status_changed', 'email', 'customer', 10, 60, true),
  ('01SEED0200CFGAPPACC0000001', '01KRERJN800000000000000001', '01SEED0200TPLAPPACC0000001',
   'Appointment accepted customer email', 'business', 'event', 'appointment.accepted', 'email', 'customer', 3, 60, true),
  ('01SEED0200CFGAPPREJ0000001', '01KRERJN800000000000000001', '01SEED0200TPLAPPREJ0000001',
   'Appointment rejected customer email', 'business', 'event', 'appointment.rejected', 'email', 'customer', 3, 60, true),
  ('01SEED0200CFGRFDAPP0000001', '01KRERJN800000000000000001', '01SEED0200TPLRFDAPP0000001',
   'Refund approved customer email', 'business', 'event', 'refund.approved', 'email', 'customer', 3, 60, true),
  ('01SEED0200CFGRFDREJ0000001', '01KRERJN800000000000000001', '01SEED0200TPLRFDREJ0000001',
   'Refund rejected customer email', 'business', 'event', 'refund.rejected', 'email', 'customer', 3, 60, true),
  ('01SEED0200CFGDLVPSH0000001', '01KRERJN800000000000000001', '01SEED0200TPLDLVPSH0000001',
   'Delivery status customer push', 'business', 'event', 'delivery.status_changed', 'push', 'customer', 10, 60, true),
  ('01SEED0200CFGTKTRDY0000001', '01KRERJN800000000000000001', '01SEED0200TPLTKTRDY0000001',
   'Ready for pickup customer email', 'business', 'event', 'ticket.ready_for_pickup', 'email', 'customer', 3, 60, true),
  ('01SEED0200CFGTKTRPS0000001', '01KRERJN800000000000000001', '01SEED0200TPLTKTRPS0000001',
   'Ready for pickup customer push', 'business', 'event', 'ticket.ready_for_pickup', 'push', 'customer', 3, 60, true),
  ('01SEED0200CFGRFDPSH0000001', '01KRERJN800000000000000001', '01SEED0200TPLRFDPSH0000001',
   'Refund approved customer push', 'business', 'event', 'refund.approved', 'push', 'customer', 3, 60, true)
ON CONFLICT (id) DO UPDATE SET
  template_id = EXCLUDED.template_id,
  config_name = EXCLUDED.config_name,
  trigger_event = EXCLUDED.trigger_event,
  channel = EXCLUDED.channel,
  recipient_type = EXCLUDED.recipient_type,
  frequency_limit = EXCLUDED.frequency_limit,
  frequency_window_minutes = EXCLUDED.frequency_window_minutes,
  is_enabled = EXCLUDED.is_enabled,
  updated_at = now();
